### ISSUE TITLE
Same method queryRPC defined twice in api.js?

### ISSUE THREAD

**Issue by mgao6767** [CityOfZion/neon-js#10]

**Comment by saltyskip** [comment]
I am also having this issue

![image](https://user-images.githubusercontent.com/14796429/29738721-85a14ad2-8a66-11e7-9654-bbf6763cb98a.png)

**Comment by mgao6767** [comment]
Yeah it's been a week nobody cares...

**Comment by canesin** [comment]
@mgao6767 we do care, the problem is the time and size constraints.. why you don`t contribute a PR to fis that ?

**Comment by mgao6767** [comment]
@canesin Honestly I knew nothing about Java, so that's why I asked why, in case it's intentionally like that. But the issue is unanswered for a while so...

If the only thing needed is to simply remove the duplicate then sure I'll submit a PR shortly. Thanks!
