### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by Ejhfast** [CityOfZion/neon-js#119]
@ixje in slack mentioned that neon-js has problems integrating with react-native (also that @totalvm may have some experience with this)

it would be great to resolve these issue so that other app developers can use the library

**Comment by ixje** [comment]
To elaborate on this;
I initially used `neon-js` in [neon-wallet-react-native](https://github.com/CityOfZion/neon-wallet-react-native) after some startup help of @snowypowers (see #18) to build it in a suitable way. This worked fine for iOS with some tweaks, but once I wanted to make it work with Android all hell broke lose. After spending 3-4 days fighting various babel errors (@totalvm also gave it some time in trying to solve those) to get it up and running I gave up an wrote my own implementation. 

Note that back then I was using `react-native` version `0.48.3` and there were a serious number of issues when it came to the babel presets on their issue tracker and SO. We're currently at `0.53-RC` so perhaps they solved some of that to make it work more easily. 

If you have any questions drop me a DM on slack or mention me here.

**Comment by MarcelBlockchain** [comment]
any updates?

**Comment by ixje** [comment]
I believe this has been working for a while now, but it's good to verify again and otherwise report whats not working. 1 thing you'll notice is that encryption/decryption of keys is not feasible on the actual device without moving that to native. You can read more about that here: https://github.com/CityOfZion/neon-wallet-react-native/issues/6
and to add to that issue; i can confirm it also works on android

**Comment by KamalHunzai** [comment]
@ixje  Neon-wallet has issues, i have tried building it.

**Comment by metachris** [comment]
See also #474

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-js/issues/474#issuecomment-669508470

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-js/issues/474#issuecomment-669932463
