### ISSUE TITLE
feat: Helper to chain multiple scripts together

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neon-js#125]
Currently, it is possible to chain multiple scripts together using the ScriptBuilder:
```
  const sb = new ScriptBuilder()
  sb
    .emitAppCall(scriptHash, 'name')
    .emitAppCall(scriptHash, 'symbol')
    .emitAppCall(scriptHash, 'decimals')
    .emitAppCall(scriptHash, 'totalSupply')
```

However, doing this requires you to be exposed to the raw working tools which is not what everyone wants to handle. This functionality is not yet exposed at a high level. 

This would be similar to the `createScript` method but take in an array of `props` instead.

## Specifics

- Define a interface describing the `props` object used in `createScript`.
- Implement a helper method with signature: `(Array<props>) => string`
- Helper method should call `emitAppCall` on each `props` object and return the final string produced by `ScriptBuilder`.
- Instead of a new helper method, it is ok to modify `createScript` if you cannot think of a better name.

**Comment by mhuggins** [comment]
This can probably be tracked as a separate issue/feature request, but would it be worth making a helper function for creating a script (or object that can be passed to `createScript`) for transferring NEP5 tokens similar to the `makeIntent` function?

**Comment by snowypowers** [comment]
yes, with the new `decimals` field being relevant now, a helper would be useful for NEP5 token transfer to avoid this pitfall
