### ISSUE TITLE
getPrice for cmc is not working properly

### ISSUE THREAD

**Issue by evgenyboxer** [CityOfZion/neon-js#140]
The endpoint of getting a price of a coin needs an `id`, not a `symbol`, so this will fail:
https://api.coinmarketcap.com/v1/ticker/eth/
while this will work:
https://api.coinmarketcap.com/v1/ticker/neo/ <-- because id is `neo`

The tests don't show this because they only use NEO/GAS, which both have the same id/symbols.

All these will fail:
https://api.coinmarketcap.com/v1/ticker/btc/
https://api.coinmarketcap.com/v1/ticker/xrp/
https://api.coinmarketcap.com/v1/ticker/ltc/

A solution might be to use only the getPrices, and filter the coin you want.

**Comment by snowypowers** [comment]
It looks like going for `getPrices` is the best solution to ensure a smooth experience because there is no way that the app will know what phrase CMC will use for each coin. We can mark this method for deprecation for now and focus efforts on `getPrices` instead.
