### ISSUE TITLE
getPrices for cmc is not showing all prices

### ISSUE THREAD

**Issue by evgenyboxer** [CityOfZion/neon-js#141]
If you try to get the price of RPX, it will not work, because cmc api returns by default only the top 100 results.
Try to look for RPX here: https://api.coinmarketcap.com/v1/ticker/ its not there.

However, if you pass a `?limit=0` to the query, it will appear - https://api.coinmarketcap.com/v1/ticker/?limit=0

Should I make a PR, introducing the limit param? or this should be just the default? (show all)

**Comment by snowypowers** [comment]
PR as default.
