### ISSUE TITLE
Adding signing for SC to transaction

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neon-js#147]
In order to manipulate assets from a smart contract address, we need certain addons to a normal `ContractTransaction`. We would like to have this as a single method under the `Transactions` class that appends the necessary addons.

Given an `adminKey` (The privatekey of the admin address) and `contractScriptHash` (the scripthash of the smart contract),

- Add an attribute of type `Script`, data being the scripthash of the `adminKey`.
- Add an signature where:
  - The invocationScript is `00` + standard invocationScript signed by `adminKey`.
  - The verificationScript is `result.script` retrieved from the `getcontractstate` call using the `contractScriptHash`.

## Specifics
- Implement method `Transaction.signAsAdmin` (name is up for discussion)
- This method should have the params: `Transaction.signAsAdmin(privateKey: string, contractScriptHash: string)`
- This method will append the relevant items mentioned above and return the `Transaction` object.

**Comment by slipo** [comment]
We also need something along the lines of ...
```
            attributes: [
              {
                usage: 32,
                data: this.reverseHex(wallet.getScriptHashFromAddress(sourceAddr))
              }
            ],
```

**Comment by slipo** [comment]
The "00" is that way because the script we were testing has 2 arguments. It needs to match the contract's parameter count.

**Comment by slipo** [comment]
A couple more notes:
* The order of the scripts is important. They need to be sorted by script hash, ascending. Otherwise the whole thing fails.
* This isn't only for admins of the script. I think it should be a method called fromContractScriptHash() or something like that which modifies the transaction and adds the attribute + script.

**Comment by snowypowers** [comment]
- Can you elaborate on the order? What do you mean by ascending?
- Is there any order to attributes ( I would suppose none but you can try adding remarks before or after)
- The main purpose is to attach a signature that verifies that the signer is authorised to carry out the action stated in the SC. Whether the method should be in the Transaction or Account Class is a tossup.

**Comment by slipo** [comment]
Sure, essentially I'm doing something like this in my custom code:
```
      if (parseInt(contractScriptHash, 16) > parseInt(sender.scriptHash, 16)) {
        signedTx.scripts.push({
          invocationScript: '00' + signedTx.scripts[0].invocationScript,
          verificationScript: script,
        })
      } else {
        signedTx.scripts.unshift({
          invocationScript: '00' + signedTx.scripts[0].invocationScript,
          verificationScript: script,
        })
      }
```

I believe that's what this is doing:
https://github.com/CityOfZion/neo-python/blob/master/neo/Core/TX/Transaction.py#L709

Without that, half my sender hashes were failing.
