### ISSUE TITLE
Some known RPCs are missing in neon-js

### ISSUE THREAD

**Issue by rockacola** [CityOfZion/neon-js#159]
While integration `neon-js` into `neo-js`, I've noticed the following RPC methods has not been implemented:

* `getBlockHash(index)`
* `getBlockSystemFee(index)`
* `sendToAddress()`

Are they excluded purposely?

**Comment by snowypowers** [comment]
Looks like i missed out `getblockhash`. `getblocksystemfee` is under `getblocksysfee`.

I havnt implemented any of the rpc calls that are more wallet functionality in general as they are hard to do integration tests to ensure the right params.

I am open to implementing them though.

**Comment by rockacola** [comment]
No worries. I can provide PR when I get around to it next week.

I can also use this opportunities to review if any new endpoints appears in `neo`s .

**Comment by rockacola** [comment]
PR #162
