### ISSUE TITLE
 CheckWitness problem with invokeScript

### ISSUE THREAD

**Issue by Said007** [CityOfZion/neon-js#163]
Hey,

All invocations that require check witness fail if used with invokeScript looking at neo-python it adds a signed transaction which CheckWitness can use.

If I add signed transaction it successfully invokes the contract this comes at cost.

I think it would be nice if test invoke can handle check witness calls.

**Comment by snowypowers** [comment]
Hi Said,

We cannot do anything about this. You should file an issue on the C# node side instead as the JS SDK is an **interaction** package, we merely communicate the parameters across, we do not run our own VM internally. As such, we are unable to emulate what neo-python can do even if we want to.

To fix this, you will have to ask neo-project to change the specification of the test invoke call.

**Comment by jeroenptrs** [comment]
@Said007 are you sending your user's hash? Using the following formatting I got my checkwitness to pass.
```javascript
const formattedAccount = u.reverseHex(
      wallet.getScriptHashFromAddress(this.account.address)
    );
```

**Comment by Said007** [comment]
@jeroenptrs Nope was sending the users address as a byteArray will try your approach of sending the users address hash

**Comment by jeroenptrs** [comment]
I had to add an extra step to the formatting for it to *actually* work. The neo-python prompt would pass it but in reality the Checkwitness wouldn't fire (thus throwing away my invocation).

I now use 1 function outside of neon-js to get my Checkwitness to actually fire and continue my application, along with the 2 previous functions:
```javascript
const address = unhexlify(
  u.reverseHex(wallet.getScriptHashFromAddress(this.account.address))
);
```
unhexlify is a function from [binascii](https://github.com/michalbe/binascii)

Post-formatting it's converted with `sc.ContractParam.string` before getting added to the `args` array. I do **not** use `sc.ContractParam.array` to cast `args` to a contract param.

If you need any more help, ping me a PM on discord 😄
