### ISSUE TITLE
Point to private net

### ISSUE THREAD

**Issue by thdxr** [CityOfZion/neon-js#165]
I've found in the codebase where neon decides what network to connect to.  However for testing I would like for it to connect to my own, is that possible?

**Comment by snowypowers** [comment]
yes it possible. ask in stackexchange or discord. issues are not a place to reach out for technical help.

**Comment by thdxr** [comment]
I've already asked in the discord several times. Since no one knew the answer I assumed it wasn't possible so I posted it here as a feature request. I wasn't asking for a tutorial. 

I still don't know the answer

**Comment by wg-git** [comment]
Hi thdxr!
I created a fork for connecting to my private-net, but you could take any address you like. There has to be an api running, of course: [fork](https://github.com/wg-git/neon-js/commits/private_net) I am using this [docker container](https://github.com/slipo/neon-wallet-db/blob/master/privnet-install.md)

**Comment by DaShak** [comment]
This page/issue is the first result when Googling  `neon-js privatenet`, so I'm commenting here with the link to CoZ's doc *Basic - Using a Private Net*:

http://cityofzion.io/neon-js/docs/en/guides/basic/privnet.html

You probably sorted it out by now, @wg-git…
