### ISSUE TITLE
[Feat] Message verification and signing

### ISSUE THREAD

**Issue by Said007** [CityOfZion/neon-js#167]
Hey,

I think adding message verification and signing would be a nice addition to this library. 

As I need to sign some content using the users Wif or private key for a DApp v2.

Wouldn't mind implementing this. 

An API along the lines
```
const signature = Neon.create.signMessage('PrivateKeyOrWiff', 'Hello World')
const verified = Neon.create.verifyMessage('NeoAddress', 'Hello World', signature)
```

or 

```
const account = new wallet.Account(privateKey)
const signature = account.signMessage('Hello World')
const verified = Neon.get.verifyMessage('NeoAddress', 'Hello World', signature)
```

Thoughts or suggestions?

**Comment by snowypowers** [comment]
probably `Neon.sign.message` and `Neon.verify.message` would be good. I think you probably can reuse some of the code for signing but verification im not so sure about that. But looks like something useful for a library!

**Comment by snowypowers** [comment]
@Said007 any progress? Do check in so I can know if you are working on it!

**Comment by Said007** [comment]
@snowypowers Been quite busy, I have working prototype which signs and verifies using elliptic.js which is pretty much very similar to generateSignature function. 

I need to write tests and do some clean ups on my code. Will make a pull request latest by end of next week.

**Comment by snowypowers** [comment]
no worries! Just checking in so we know whats being worked on. 

In the meantime, would be good to have a sketch of what to expect:

- Method signature
- Method name
- location within the package

**Comment by Said007** [comment]
Within the wallet module. 

message.js

```
/**
 * Generates a signature of the message based on given private key.
 * @param {string} message 
 * @param {string} privateKey
 * @return {string} Signature
 */
export const signMessage = (message, privateKey) => {
  /// Sign and generate message signature using elliptic p256
}

```

```
/**
 * Verifies signature matches message and is valid for a given public key.
 * @param {string} message
 * @param {string} publicKey
 * @param {string} signature
 * @return {boolean}

 */
export const verifyMessage = (message, publicKey, signature) => {
  // verify publicKey, message, signature match using elliptic p256
}
```

What do you think? any remarks?

**Comment by snowypowers** [comment]
Looks good. Try to accept both formats for private key (WIF and HEX). Similarly, you should check and accept both forms of public key too (encoded and unencoded)

**Comment by snowypowers** [comment]
Thanks for your contribution!
