### ISSUE TITLE
[Docs] More tutorials

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neon-js#179]
Tutorials are working out to be a lot better than clunky auto-generate API reference. 

Tutorial articles can come in 2 forms: 
- Explaining how to use `neon-js` in a specific manner
- Explaining how a specific part of NEO works

**Comment by jeroenptrs** [comment]
@snowypowers I'd love to work on doInvoke! Also, invocationtransactions in general, since I had a ton of work done on it with my [Neoblog project](https://github.com/be-neo/neoblog).

**Comment by jeroenptrs** [comment]
#191 added basic doInvoke guide

**Comment by jeroenptrs** [comment]
@snowypowers NEP-5 tutorial would be nice?

**Comment by snowypowers** [comment]
I do think the `doInvoke` tutorials covers most of it. We can adjust them instead. Unless you have something more in mind?
