### ISSUE TITLE
feat(api): Notifications query

### ISSUE THREAD

**Issue by Said007** [CityOfZion/neon-js#188]
Hey @snowypowers 

Adding the Notifications query to the API module is nice feature for implementing pure js app without middleware.

The option to query Notifications by contract, address, tx ect.

I Could implement this for next Q2 if their is a need for it in this library.

?

**Comment by Said007** [comment]
Their is an endpoint which allows you to retrieve notifications http://notifications.neeeo.org/ or http://testnotifications.neeeo.org/

The concept is very similar to getting the balance you can use pass endpoint or use Neoscan.

So Notifications object will use neeeo.org to query notifications or a custom endpoint which is running a full node.

**Comment by snowypowers** [comment]
This seems it can be a simple seperate API setup. There isn't anything that requires any sepcial transformation from neon-js, nor does neon-js require it specifically to activate any functionality. 

If we can ensure the spec is consistent and up to date we can build off that. The only thing i would not provide is to provide a default endpoint unless that endpoint is hardened enough.

**Comment by Said007** [comment]
Am not sure if the specification is going to be consistent unless coz is running neeeo.org so I guess we can close this issue off or coming back to in the future.
