### ISSUE TITLE
[Docs] /master/docs/api-api.md

### ISSUE THREAD

**Issue by CHAOWEICHIU** [CityOfZion/neon-js#193]
It seems like the API documentation is a little behind.

I would like to update it and some example for it

For example
`https://github.com/CityOfZion/neon-js/blob/master/docs/api-api.md#coinmarketcap`

On the doc
```
import Neon from '@cityofzion/neon-js' .        // No longer work
Neon.get.price('NEO', 'EUR')                             // No longer work
Neon.get.price('GAS') // defaults to USD        // No longer work
Neon.get.prices(['NEO', 'GAS'], 'EUR')            // No longer work
Neon.get.prices(['NEO', 'GAS']) // defaults to USD // No longer work

import { api } from '@cityofzion/neon-js'
api.cmc.getPrice('NEO', 'SGD') .                     // It is promise base
api.cmc.getPrices(['NEO', 'GAS'], 'SGD') .     // It is promise base
```

**Comment by snowypowers** [comment]
Hi can you clarify how does it `no longer work`? Those are all promises and are used by NEON wallet. They seem to be working as far as I can tell.

**Comment by CHAOWEICHIU** [comment]
It seems like you cannot use `Neon` does not have `get` method anymore.

I would have to use `Neon.default.get...` instead of `Neon.get...`

**Comment by snowypowers** [comment]
are you using `import` or `require`?
Do refer to http://cityofzion.io/neon-js/docs/en/installation.html#import

**Comment by CHAOWEICHIU** [comment]
I was using `require` instead of `import`

thanks for the link !

**Comment by CHAOWEICHIU** [comment]
Do you think it might be a good idea to provide both example somewhere?

**Comment by snowypowers** [comment]
Well isnt that link both examples? Do clarify your question.

**Comment by CHAOWEICHIU** [comment]
Yeah, I mean do you think it might be a good idea to add a link somewhere in this repo?

**Comment by snowypowers** [comment]
the readme does have a link to the docs.

**Comment by CHAOWEICHIU** [comment]
ok thanks
