### ISSUE TITLE
[Feature] Implement ICO methods

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neon-js#194]
The release of the [NEX ICO Template](https://github.com/neonexchange/neo-ico-template) introduces several handy methods that are interesting. Specifically,the crowdsale handling methods that allow the client to check if the sales is active and if the address is whitelisted.

While this set of methods are not an official standard, the rise of contracts following these set of standard has been increasing and it is beneficial to include them as part of the API offering.

## Specifics

- Comb through the NEX ICO template and find the methods to implement. Focus on methods that are useful from a client perspective (what methods are useful for a light wallet?)
- These methods are to belong in the `api/crowdsale.js` file.

## References
- The methods you are crafting are probably similar to what is found in `api/nep5.js`

**Comment by jeroenptrs** [comment]
I'll go through the template later this week if that's 🆗 . 👌

**Comment by jeroenptrs** [comment]
@snowypowers so there are three functions that seem interesting to me, two of which are crowdsale related:
* `crowdsale_status`: gets the KYC Status of an address
* `crowdsale_available`: the amount of tokens left for sale in the crowdsale

This one is more general, but seems interesting to add as well:
* `circulation`: the total amount of tokens in circulation

The rest are token owner functions

**Comment by snowypowers** [comment]
I have just read through the Orbis Contract and while it is nice that they are using C#, there is now a difference in methods:

Python:

`crowdsale_status` returns a boolean or a integer depending on whether have you contributed.
`crowdsale_available` returns an integer

C#:

`checkKYC` is the equivalent of `crowdsale_status` but returns strings 'on' or 'off'
C# does not offer the `crowdsale_available` equivalent

**Comment by jeroenptrs** [comment]
hmm, that's stupid. Is it still worth it implementing this if there are no standards in KYC/crowdsale operations?

**Comment by snowypowers** [comment]
There isn't but an implementation will help consolidate it. This won't have enough impact to be a NEP but implementation and support will make it easier for the community to come together. This is a good chance for discussion about some standardization.

**Comment by jeroenptrs** [comment]
In regards of achieving consensus - even if it's not impactful enough - wouldn't it be best to propose it as a NEP? Or spark the flame in the community to get it close to a NEP proposal?
