### ISSUE TITLE
[Feature] RPC Node Discovery

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neon-js#196]
We want to have some sort of discovery mechanism for neon-js to be able to independently decide on the best RPC node to hook onto.

Currently, we rely on neon-wallet-db or neoscan to provide a best node URL. However, `best` merely means best in terms of block height. We also want to be able to function independently to determine the best node ourselves.

## Specifics

- Given only the seed nodes, discover new nodes and collate them.
- Identify open RPC ports on nodes and determine if the network is the same (nodes can host different networks running on different ports)
- Do a latency and blockheight test to detemine if the node is `good enough`.

**Comment by CHAOWEICHIU** [comment]
I have figured someone have made the list of all available RPCs at `https://raw.githubusercontent.com/CityOfZion/neo-mon/master/docs/assets/mainnet.json`

What do you think of the implementation 
```javascript
getRpcsLatencyWithin(1000)
.then(urls=>urls.sort((a,b)=> a.result + b.result)[0])  // take the one that has the most block height
.then(url => {
  url // { jsonrpc: '2.0', id: 'https://seed1.switcheo.network:10331', result: 2140235 }
})
```

**Comment by snowypowers** [comment]
I would prefer to rely on the network itself. Being a library means we should avoid as many hard coded stuff as possible.

**Comment by CHAOWEICHIU** [comment]
Just a thought, do you think it is a good idea to have that implementation in place first in order to have better developer experience when they are using neon-js SDK. 

I think it would be better than `hard-code` RPC endpoint.

In the future, we could totally swap the underline implementation with no dependency.

**Comment by snowypowers** [comment]
that would be nice. Though I think that the proper way is to provide the interface where you can have a `Network` class which holds the RPC endpoints and a separate method call to fill this Network class with RPC addresses. This way, the user can choose whether he wants to trust the COZ list or provide their own list (they might want to use their private nodes for example).

Are you looking to work on this? Else I will start working on building up the Network class.

**Comment by CHAOWEICHIU** [comment]
Yeah, let me work on `Network` class.

**Comment by CHAOWEICHIU** [comment]
For how a user could use Network, they can either use the list from COZ or they could give it to the class and we will help out to pick the best from for them.

```
const network = new rpc.Network({
  net: 'MainNet',
})
network
.getBestRPCWithLatency(2000)
.then(rpc => {
  /*
    {
      "jsonrpc": "2.0",
      "id": "https://pyrpc4.narrative.network:443",
      "result": 2201392
    }
  */
})

const personalNetwork = new rpc.Network({
  nets: [
    { url: 'pyrpc4.narrative.network', port: 443 },
    { url: 'seed1.neo.org', port: 20331 },
  ] 
})
personalNetwork
.getBestRPCWithLatency(5000)
.then(rpc => {
  /*
    {
      "jsonrpc": "2.0",
      "id": "https://pyrpc4.narrative.network:443",
      "result": 2201392
    }
  */
})
```

**Comment by CHAOWEICHIU** [comment]
- We will not be including the list in the codebase so we need a api call to retrieve the list.
  - Yes, it would be a API call to get the list
  - For MainNet, https://raw.githubusercontent.com/CityOfZion/neo-mon/master/docs/assets/mainnet.json
  - For TestNet, https://raw.githubusercontent.com/CityOfZion/neo-mon/master/docs/assets/testnet.json'

- We probably want a way to add new rpc addresses to an existing network. the MainNet Network object already exists so we might not want to override it with a new object.
  - What about providing more method to existing class of Network, that way, we could have backward compatibility

- `getBestRPCWithMaxLatency()`
```
Class Network {
  ...
  /**
   * Get the best RPC base on block height and latency
   * @param {int} maxLatency Maximum Lantency among all the networks 
   * @returns {string} Best RPC endpoint
   */
  getBestRPCAddress({ maxLatency = 5000 }){
    ...
  }
  ...
}

// How to use this?
const network = new rpc.Network({
  net: 'MainNet',
})
network
.getBestRPCAddress({maxLatency: 2000})
.then(rpcEndpoint => {
  console.log(rpcEndpoint) // https://pyrpc4.narrative.network:443
})

```
- nets is not the appropriate name for a list of rpc addresses.
  - What about ...
```
const config = {
  net: 'CustomNet',
  extra: {
    addresses: [
      'https://pyrpc4.narrative.network:443',
      ...
    ]
  }
}
```

**Comment by snowypowers** [comment]
- Do include the API call in this design.
- Yes having a method to add rpc addresses would be ideal.
- Your docstring declares an integer argument but your example uses an object argument. Please decide on one and justify.
- im fine with `addresses`. My alternative is `rpcs`

**Comment by snowypowers** [comment]
@CHAOWEICHIU any updates?

**Comment by CHAOWEICHIU** [comment]
- Do include the API call in this design. 
  - ok
- Yes having a method to add rpc addresses would be ideal.
  - ok
- our docstring declares an integer argument but your example uses an object argument. Please decide on one and justify.
  - I think it is good to just return `url`
- im fine with addresses. My alternative is rpcs
  - I will be using rpcs, because it is much more related to what it does

**Comment by ishwarchandratiwari** [comment]
What is rpc here?

const network = new rpc.Network({
  net: 'MainNet',
})
network
.getBestRPCWithMaxLatency(2000)
.then(rpc => {
  console.log(rpcEndppoint) // https://pyrpc4.narrative.network:443
})

**Comment by phetter** [comment]
This code needs refactoring, but you may find my work on neotools helpful. I've written a bunch of tools to pull all the stats of nodes. This needs to be rewritten to just pull all the data then rank based on that, but the basic functionality is there.

https://github.com/CityOfZion/neo-tools/blob/dbf9c55ca8598f9550df135cf6cd4a5f15d4c769/src/nodejs/neo-rpc/v2.9.0/client/module/getNodesBy.js
