### ISSUE TITLE
[Use case] P2P Transaction sharing

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neon-js#197]
Currently transactions are free on the NEO network. However, there comes a day where transaction fees are imposed and people will want to share transactions in order to save on fees. 

This also increases anonymity as multiple pooled transactions obscures intent.

I don't expect this to be a PR but rather a standalone project with probably a matchmaking server.

## Specifics

- In a P2P way, discover other people willing to share transaction fees
- Collate and broadcast the transaction to be signed
- Ensure that the transaction is signed and sent properly
- Possible onion algorithm where a pool of address collude to obscure sending intents.

**Comment by igormcoelho** [comment]
Very good idea @snowypowers! I hope seeing that implemented sometime! :)
