### ISSUE TITLE
API Typo for scriptBuilder

### ISSUE THREAD

**Issue by CHAOWEICHIU** [CityOfZion/neon-js#205]
Issue:
`scriptBuilder is not a function but a class`

Uri:
`https://github.com/CityOfZion/neon-js/blob/master/docs/api-sc.md#scriptbuilder`

Solution:
From
`const sb = Neon.create.scriptBuilder()`
To
`const sb = new Neon.create.scriptBuilder()`

**Comment by snowypowers** [comment]
This is an non-issue if you refer to the code. the create function is a wrapper so we don't have to `new` in the semantic version.

Do verify your issue against code. A simple test would have done it.
