### ISSUE TITLE
CoZ wallet's API returns wrong data today

### ISSUE THREAD

**Issue by Chubby-Chocobo** [CityOfZion/neon-js#211]
Today I couldn't create invocation transaction. Seems the problem is `api.neonDB.getBalance` doesn't return correct data.
When trying to request http://api.wallet.cityofzion.io/v2/address/balance/AYDgRmQfJ6Her1QpwuG81uSoG52CPTcEzK
It said the balance is 0.5 GAS:
```
{
  "GAS": {
    "balance": 0.5,
    "unspent": [
      {
        "index": 1,
        "txid": "9818c2827cc0747ce37df5532a500ad0312677683f1a65acf0967a8aa8788991",
        "value": 0.5
      }
    ]
  },
  "NEO": {
    "balance": 0,
    "unspent": []
  },
  "address": "AYDgRmQfJ6Her1QpwuG81uSoG52CPTcEzK",
  "net": "MainNet"
}
```
But actually the balance is 10.5 GAS:
https://neoscan.io/address/AYDgRmQfJ6Her1QpwuG81uSoG52CPTcEzK
https://neotracker.io/address/AYDgRmQfJ6Her1QpwuG81uSoG52CPTcEzK

Could anyone help to check this issue? Thank you very much.

**Comment by snowypowers** [comment]
it was an issue with neonDB.
