### ISSUE TITLE
getBalance() response with incorrect GAS value

### ISSUE THREAD

**Issue by rockacola** [CityOfZion/neon-js#22]
The `response.GAS.balance` of `API.getBalance()` method may be suffering from float imprecision bug.

To replicate:

* Attempt to fetch `balanceOf` `ALfnhLg7rUyL6Jr98bzzoxz5J7m64fbR4s` from `TESTNET`.
* Notice request to `http://testnet-api.neonwallet.com/v2/address/balance/ALfnhLg7rUyL6Jr98bzzoxz5J7m64fbR4s`,
* and response as (or similar):
```
{ Neo: 66,
  Gas: 56.076767890000006,
  unspent: ... TRUNCATED ...
```
* Compare with direct request to NEO's JSON-RPC:
```
result: { version: 0,
  script_hash: '0x5df31f6f59e6a4fbdd75103786bf73db1000b235',
  frozen: false,
  votes: [],
  balances:
   [ { asset: '0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b',
       value: '66' },
     { asset: '0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7',
       value: '56.07676789' } ] }
```

**Comment by snowypowers** [comment]
Closing as this issue seems to be resolved.
