### ISSUE TITLE
sendAsset fails due to duplicate input in tx

### ISSUE THREAD

**Issue by DalderupMaurice** [CityOfZion/neon-js#220]
Sending an asset utilizing the `sendAsset` function results in a failed transaction probably (not certain) due to a duplicate in the tx object.

Steps to reproduce: 
```
  const intents = api.makeIntent({ GAS: 1 }, "anyAddress");

  const config = {
    net, // "TestNet"
    address, // "Address of the receiver"
    privateKey: wif, // "Private key of the receiver"
    intents // intent from makeIntent
  };

  const response = await api.sendAsset(config);
```

Where `response.result` results in a `false`.
Looking at the `response.tx` we can see a duplicate entry in the `inputs` field.

The issue does not arise with version `3.3.3`, but does arise in later versions.

**Comment by jeroenptrs** [comment]
@snowypowers I'm going to look into this together with @DalderupMaurice!

**Comment by jeroenptrs** [comment]
It works with changes currently on **dev** 🎉
