### ISSUE TITLE
[Docs] NEP5 related methods 

### ISSUE THREAD

**Issue by CHAOWEICHIU** [CityOfZion/neon-js#221]
It seems like that we dont have method for using nep5 related example.

I could write a doc for it if you think it is a good idea.

**Comment by snowypowers** [comment]
Do elaborate on your plan. I don't see much complication in calling a method with parameters. Are you looking to improve an existing page or create a new page?

**Comment by CHAOWEICHIU** [comment]
I just found the doc, 
its at https://github.com/CityOfZion/neon-js/blob/master/docs/api-api.md#nep5
