### ISSUE TITLE
getTransactionHistory() only returns up to 25 transaction records.

### ISSUE THREAD

**Issue by rockacola** [CityOfZion/neon-js#23]
getTransactionHistory() only returns up to 25 transaction records regardless of numbers of transactions within an address. Method also doesn't seems to take optional parameters for pagination supports.

To replicate:
* Attempt to fetch `getTransactionHistory` `ALfnhLg7rUyL6Jr98bzzoxz5J7m64fbR4s` from `TESTNET`.
* Notice request to `http://testnet-api.neonwallet.com/v2/address/history/ALfnhLg7rUyL6Jr98bzzoxz5J7m64fbR4s`,
* and also notice the result array length at `25`, despite https://neoscan-testnet.io/address/ALfnhLg7rUyL6Jr98bzzoxz5J7m64fbR4s shows there are 1000+ transaction records.

**Comment by snowypowers** [comment]
this is a limit on the API side, not with this library. You can find it @ https://github.com/CityOfZion/neon-wallet-db/blob/master/api/api.py#L173

**Comment by rockacola** [comment]
I thought that might be the case (of conscious limitation), at the same time there's no documentations state that the `limit(25)` is a desirable effect on the API endpoint or developer error.

Should this be bubbled up to `neon-wallet-db` instead?

**Comment by snowypowers** [comment]
Yes, there is nothing that can be done on this side.

**Comment by rockacola** [comment]
@snowypowers, thank you.

Related issue created in `neon-wallet-db`.

**Comment by Ejhfast** [comment]
thanks @rockacola, this is on db side for performance reasons
