### ISSUE TITLE
npm i @cityofzion/neon-js  install module failed.

### ISSUE THREAD

**Issue by cymonx** [CityOfZion/neon-js#240]
C:\NodeJs\neo\neon-js>npm i @cityofzion/neon-js
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "@cityofzion/neon-js" under a package
npm ERR! also called "@cityofzion/neon-js". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     %AppData%\Roaming\npm-cache\_logs\2018-05-08T13_53_46_639Z-debug.log

**Comment by snowypowers** [comment]
i think the error message is pretty clear - don't install the package in a folder with the same name.
