### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by gonmf** [CityOfZion/neon-js#242]
Hello, I'm trying to execute the code bellow:

```
config = {
      net: 'TestNet',
      script: Neon.create.script({
        scriptHash: 'de1a53be359e8be9f3d11627bcca40548a2d5bc1',
        operation: 'registerMailbox',
        args: [
          Neon.u.reverseHex(Neon.u.str2hexstring(neoWallet.getPublicKey(true))),
          Neon.u.reverseHex(Neon.u.str2hexstring('some string'))
        ]
      }),
      address: neoWallet.address,
      privateKey: neoWallet.privateKey,
      gas: 0
    };

    Neon.doInvoke(config).then(res => {
      console.log(res.response);
    });
```

And am getting errors like:

`Request header field timeout is not allowed by Access-Control-Allow-Headers in preflight response.`

Any idea?

**Comment by snowypowers** [comment]
Will need more information about your environment. I ran a script in node console and browser console and they worked out fine.

**Comment by gonmf** [comment]
My environment was a rails app with the package compiled by browserify, but I'll try again later today.

**Comment by snowypowers** [comment]
I found a small mistake that I made that might have caused this issue. Do try 3.7.2.

**Comment by gonmf** [comment]
I can't seem to be able to upgrade to 3.7.2

**Comment by snowypowers** [comment]
sorry, there was some issue with publishing. It should be available now.

As for your question, there is no such type as `Address` for contract param. I guess that is where it went wrong. You should be using a bytearray to pass the address in. I would try `Neon.sc.ContractParam.byteArray(neoWallet.address, 'address')`

**Comment by gonmf** [comment]
Using that method to send the address didn't solve the issue unfortunately. Do you think it needs at least 1 GAS? Or Neon.create.script to encapsulate the value of the script?

**Comment by snowypowers** [comment]
It is possible that you will need GAS if your script overruns. However, the behavior for that should be that the transaction should still goes through (the method returns `true`) because transaction acceptance is independent of script success. The only other thing that blocks transaction acceptance is verification. Are you using verification in your contract? 

`doInvoke` will read the script object and parse it for you, so passing in a hexstring or a object will work.

On a side note, it seems that you are unsure if your script needs additional GAS attached. Have you tried using a testinvoke to check how much GAS your script uses? Do note that test invokes do not work if the method requires verification.

**Comment by corck** [comment]
is it possible that this still exists for some requests. I'm trying to do a `sendAsset` and it fails with that error message. I'm using the [slipo docker](https://github.com/slipo/neo-scan-docker) setup

    let WIF_KEY = "XXXXXXXXXX";
    let account = new wallet.Account(WIF_KEY);
    console.log(account)

    function signTx(tx, publicKey) {
      return Promise.resolve(tx.sign(account.privateKey));
    }

    const contractAddress = 'XXXXXXXX';
    const destinationAddress = 'XXXXXXXX';

    const intents = api.makeIntent({NEO: 1}, destinationAddress);

    const txConfig = {
      url: 'http://localhost:4000/api/main_net',
      net: 'PrivateNet',
      address: account.address,
      intents: intents,
      fees: 0.1,
      sendingFromSmartContract: true,
      publicKey: account.publicKey,
      privateKey: account.privateKey,
      signingFunction: signTx
    }

    api.sendAsset(txConfig)
      .then(config => {
        console.log(config);
      })
      .catch(config => {
        console.log(config)
      });
  }

**Comment by corck** [comment]
my app was using a cached version, so all good with the latest versions.

**Comment by mhuggins** [comment]
This issue occurs sporadically depending on the endpoint selected by neon-js.  I've run into this as well.  I haven't dug into it, but I suspect it's either an issue with specific endpoint versions, or with the server setup around that endpoint.
