### ISSUE TITLE
Unable to get Balance object on Testnet

### ISSUE THREAD

**Issue by conscott** [CityOfZion/neon-js#263]
It seems 
```
api.neonDB.getBalance('TestNet', addr)
```
 times out and 
```
api.neoscan.getBalance('TestNet, addr) 
```
is unable to find balances for Testnet Addresses that do have a NEO/GAS balance

Because of this, I am unable to test http://cityofzion.io/neon-js/docs/en/adv_multitx.html

Additionally, trying to use `intents` with `doInvoke` fails because it gets:

"This balance does not contain any GAS!" (even though it does).

**Comment by phetter** [comment]
FYI I can't reproduce this as described above when testing directly against neoscan-testnet.io/api/test_net/v1/get_balance/address.

A new account that has no balance yields the following:

![screen shot 2018-05-30 at 1 05 50 pm](https://user-images.githubusercontent.com/7162325/40735863-5ce7ef32-640a-11e8-9af8-a0c3625edde6.png)

An old account that has balance shows up fine:

![screen shot 2018-05-30 at 1 05 04 pm](https://user-images.githubusercontent.com/7162325/40735865-5d8d4ed2-640a-11e8-88fc-33c1e138a55a.png)

I reviewed the neoscan.js code at 

https://github.com/CityOfZion/neon-js/blob/c6a169a82a4d037e00dccd424f53cdc818d6b3ae/src/api/neoscan.js#L70

and I must admit I don't understand why that line is even there. It appears to return a new balance if the address **does not** match the response.data.address **and** if the balance is null. 

I was working on something related and thought I'd share my 2 cents. 

Salud

**Comment by conscott** [comment]
Thank you for the response. 

For my address I am looking at `AL8abuPwBMmmvaj1EttZr6B6R7NDoXBsm6`, the RPC interface gives expected balance:
```bash
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"getaccountstate", "params": ["AL8abuPwBMmmvaj1EttZr6B6R7NDoXBsm6"], "id": 3}' seed2.neo.org:20332
```

but NeoScan API does not:
[https://neoscan-testnet.io/api/test_net/v1/get_balance/AL8abuPwBMmmvaj1EttZr6B6R7NDoXBsm6](https://neoscan-testnet.io/api/test_net/v1/get_balance/AL8abuPwBMmmvaj1EttZr6B6R7NDoXBsm6)

Curious if anyone knows why.

**Comment by phetter** [comment]
That would be an issue with https://github.com/CityOfZion/neo-scan. Maybe open an issue there.

**Comment by conscott** [comment]
You are right. Have opened an issue there :) 

Closing this one.
