### ISSUE TITLE
Cannot claim gas from smart contract

### ISSUE THREAD

**Issue by Chubby-Chocobo** [CityOfZion/neon-js#266]
I have a smart contract with some unclaimed GAS on mainnet.
To claim them all, I use these code:
```js
  // Public address of smart contract
  const contractAddress = 'XXX';
  // Private key of contract's owner (account that was used to deploy contract)
  const ownerPrivateKey = 'YYY'; 

  const config = {
    net: 'MainNet',
    address: contractAddress,
    privateKey: ownerPrivateKey,
    sendingFromSmartContract: true
  };

  api.claimGas(config)
    .then(res => {
      console.log(res.response);
    })
    .catch(err => {
      console.log(`[ERROR] ${err.toString()}`);
    })
```

But I always got the false result:
```js
{ jsonrpc: '2.0', id: 1234, result: false }
```

I tried `sendAsset` method with same address and private key and it works, but `claimGas` is always failed.
Could anyone give me some suggestion to resolve this issue?
Thanks.

**Comment by snowypowers** [comment]
Looks like i missed out amending the claimGas method for acting as smart contract. Will patch this up in the next patch.

**Comment by snowypowers** [comment]
hi try it out with 3.9.1. I just added the support in claimGas method.

**Comment by Chubby-Chocobo** [comment]
It works now. Thanks for your help.
