### ISSUE TITLE
getBalance doesnt seem to work on TestNet

### ISSUE THREAD

**Issue by Marxpark** [CityOfZion/neon-js#272]
api.neonDB.getBalance(net, addr) only seems to work on MainNet. 

api.neonDB.getBalance('MainNet','AQ9GeL84C8P4XwgejrPBZoYdvgRLZyxKM9') returns a Balance object that i can further work with, whereas api.neonDB.getBalance('TestNet','AQ9GeL84C8P4XwgejrPBZoYdvgRLZyxKM9') returns an error Request failed with status code 503.

What can I do about this?

**Comment by kashyap2690** [comment]
I am also getting 503 when trying to call smart contract with doInvoke. 
503 is for url http://testnet-api.wallet.cityofzion.io/v2/network/nodes
Any help?

**Comment by snowypowers** [comment]
neonDB service will be deprecated within this week. Please switch over to using neoscan instead. There shouldn't be much impact in terms of code as both providers are coded under the same interface.

**Comment by kashyap2690** [comment]
How to switch over neoscan? I know it is already configured in the network.json, but how to use neoscan not neonDB?

**Comment by rappad** [comment]
i've got this problem too, please clarify

**Comment by snowypowers** [comment]
neoscan api lives under `api.neoscan`

**Comment by Marxpark** [comment]
api.neoscan returns empty balance. I recently found out that there is a CoZ testnet, but i'm sure i have my funds on the Neo testnet because i filled out their form, not the CoZ one. My testnet address is AQ9GeL84C8P4XwgejrPBZoYdvgRLZyxKM9, and i made the test funds claim successfully, yet i can only see my assets running the Neo python from CoZ -> np prompt, open wallet, wallet -> 
"addresses": [
        {
            "version": 0,
            "script_hash": "AQ9GeL84C8P4XwgejrPBZoYdvgRLZyxKM9",
            "frozen": false,
            "votes": [],
            "balances": {
                "0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b": "100.0",
                "0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7": "5000.0"
            },
            "is_watch_only": false
        },
        {
            "address": "AZxQqsnqdRVnGfyxwNwqMkLFmjTD1yDBtA",
            "script_hash": "c77077090cdaa50bdcbc00453a7ff015525db5d3",
            "tokens": null
        }
    ],
The result of api.neoscan.getBalance('TestNet','AQ9GeL84C8P4XwgejrPBZoYdvgRLZyxKM9') however, is 
blance:
  address: "AQ9GeL84C8P4XwgejrPBZoYdvgRLZyxKM9"
  assetSymbols:[]
  assets:{}
  net:"TestNet"
  tokenSymbols:[]
  tokens:{}

Am i doing something wrong?
