### ISSUE TITLE
TestNet is not working

### ISSUE THREAD

**Issue by itbeckham7** [CityOfZion/neon-js#278]
- This is my code
const rpcEndpointPromise = neoAPI.neonDB.getRPCEndpoint('TestNet');

- This is error message.
(node:17740) UnhandledPromiseRejectionWarning: Error: timeout of 5000ms exceeded
    at createError (M:\cronus\node_modules\@cityofzion\neon-js\lib\index.js:895:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (M:\cronus\node_modules\@cityofzion\neon-js\lib\index.js:318:16)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
(node:17740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async fu

- I think that 
"neonDB": "http://testnet-api.wallet.cityofzion.io",
"neoscan": "https://neoscan-testnet.io/api/test_net"
this is not working now.
Please check it and help me.

- My other problem
i am going to transfer nep5 token.
symbol: CRO9
hash: 36d7c487c029d152da8d86aa22d922c1d7d73ce8
could you give me sample code for transfer this token?
thanks.

**Comment by jonatanblockchain** [comment]
Not sure if its related: https://www.reddit.com/r/NEO/comments/8vkxy5/important_psa_apineonwalletcom_is_officially/

**Comment by snowypowers** [comment]
As mentioned by jonatan, neonDB service is offline. Please switch over to neoscan using `api.neoscan`.

Please read the docs on how to construct invocations transactions. That should help you figure it out.
