### ISSUE TITLE
创建NEP5交易

### ISSUE THREAD

**Issue by huachao0326** [CityOfZion/neon-js#279]
您好，请问新建一个NEP5交易是使用createInvocationTx吗？有没有例子？

**Comment by snowypowers** [comment]
对 createInvocationTx 是可以用的。neon-js 有个简单化的方法叫doInvoke， 例子只有英文版：

http://cityofzion.io/neon-js/docs/en/basic_invoke.html

**Comment by huachao0326** [comment]
let tran = tx.Transaction.createInvocationTx(
        api.neoscan.getBalance('TestNet','AS2oHnBGNybMXJBLEj23K6MZBu2QgKtLc4'),//Balance of address
        api.makeIntent({NEO:1},'AcjTaHQdMo3jv8PDAZACTYnqo7rqUuo8um'),//output
        'ecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9',
        0,
        null);
如果我想转账5个RPX，api.makeIntent()这里是添NEO:5,还是RPX:5?
执行这个的时候返回
TypeError: Cannot read property 'indexOf' of undefined
"This balance does not contain any "

**Comment by snowypowers** [comment]
No, `makeIntent` is only used for native assets, you need to construct an invocation script for NEP5 tokens. Please follow the guide for basic invoke and extend it to making a `transfer` script. There are also examples within the test suite.
