### ISSUE TITLE
Missing progressCallback on higher functions

### ISSUE THREAD

**Issue by Satoshinaire** [CityOfZion/neon-js#28]
Looking at the NEP2 implementation (nice work, thanks!) I noticed that `encrypt` and `decrypt` had `progressCallback`s (which have since been removed in #17 ).

Given that they can take a while, especially on low-powered machines:

a) Why weren't they passed to higher functions for more convenient use?
b) Why have they been removed altogether?

**Comment by Satoshinaire** [comment]
@snowypowers I guess you might be able to answer this 😄

**Comment by snowypowers** [comment]
1. How it works is that you pass in the callback and the `decrypt` function will call it at intervals  passing in the progress. This is helpful if you were using the async version of scrypt.

2. The arguments were copied directly from my implementation of NEP2. Neon chose to use another version of scrypt which did not support such an arg. Furthermore, the method we are calling is the sync version and does not support callbacks. Thus, we remove it to clean up the code.

**Comment by Satoshinaire** [comment]
That makes sense. I wish it was there though 😛
