### ISSUE TITLE
createInvocationTx

### ISSUE THREAD

**Issue by huachao0326** [CityOfZion/neon-js#282]
const neon = require('@cityofzion/neon-js');
const Neon = neon.default;
let props = {
        scriptHash: 'ceab719b8baa2310f232ee0d277c061704541cfb',
        operation: 'transfer',
        args: [neon.wallet.getScriptHashFromAddress('ATbQJunyh73EFFgSKwsPpRc3wqQEfgHDN5'),neon.wallet.getScriptHashFromAddress('AXEZ3zPLrJo12wLi1zr6K7sQLVbiACQth2'),10]
    };
    let vmScript = Neon.create.script(props);
    let balance = neon.api.neoscan.getBalance('MainNet', 'ATbQJunyh73EFFgSKwsPpRc3wqQEfgHDN5');
let unsignedTx = neon.tx.Transaction.createInvocationTx(balance, null, vmScript, 0);

执行的时候报错：TypeError: e.applyTx is not a function。麻烦帮忙看下，谢谢

**Comment by snowypowers** [comment]
`neon.api.neoscan.getBalance` returns a Promise.

**Comment by huachao0326** [comment]
neon.api.neoscan.getBalance('MainNet', 'ATbQJunyh73EFFgSKwsPpRc3wqQEfgHDN5');
返回PromiseStatus:pending PromiseValue:undefined

**Comment by huachao0326** [comment]
neon.api.neoscan.getBalance('MainNet', 'ATbQJunyh73EFFgSKwsPpRc3wqQEfgHDN5').then(response => {
        console.log('=============');
        let unsignedTx = neon.tx.Transaction.createInvocationTx(response, null, vmScript, 0);
        console.log('=============');
        let signedTx = neon.tx.signTransaction(unsignedTx, ecPair.d);
        console.log('=============');
    });
log不打印

**Comment by snowypowers** [comment]
It works on my side. Please check if your connection to neoscan is working.
