### ISSUE TITLE
Basic - Create Smart Contract Script (outdated ? )

### ISSUE THREAD

**Issue by 4math2379** [CityOfZion/neon-js#298]
Hi ,

On your website about Smart contract it is wrote : 

> Do note that this template is very outdated and should not be used as an actual ICO template.

For a private services i can use it ? or what kind of issues i can encounter for a public ICO ?

Thanks

**Comment by snowypowers** [comment]
It is usable but it is not maintained thus it does not contain any bugfixes found. 

You should be looking at some of the newer templates if you are planning anything more than a personal project.
