### ISSUE TITLE
getapplicationlog error

### ISSUE THREAD

**Issue by KanishTheVista** [CityOfZion/neon-js#300]
when i was doing 

curl -X POST \
  http://seed5.cityofzion.io:8080 \
  -H 'Content-Type: application/json' \
  -d '{
  "jsonrpc": "2.0",
  "method": "getapplicationlog",
  "params": ["0xd1c7ea5f406e0f3ade3e8a9cd575a7b08a73f440ede947d16c325c09eaedb33e"],
  "id": 1
}

its was giving :: {"jsonrpc":"2.0","id":1,"error":{"code":-100,"message":"Unknown transaction"}}
is there any issues with 'Cityofzion' SEED node?

**Comment by snowypowers** [comment]
this is the wrong place to get help for such issues. Please use discord.
