### ISSUE TITLE
Support block due limit on transactions

### ISSUE THREAD

**Issue by igormcoelho** [CityOfZion/neon-js#311]
It would be nice to have support to due time in transaction created on neon-js! This issue was discussed here (https://github.com/neo-project/neo/issues/371), and would prevent transactions to "stay forever" on relay nodes if network is overloaded. For now, I'm just registering the idea, but I can help to implement it, on future free times :)

**Comment by bpetridis** [comment]
Completely agree, timeouts are a standard across other mediums, don't see why they shouldn't be included in this fashion also.

**Comment by bpetridis** [comment]
> It would be nice to have support to due time in transaction created on neon-js! This issue was discussed here ([neo-project/neo#371](https://github.com/neo-project/neo/issues/371)), and would prevent transactions to "stay forever" on relay nodes if network is overloaded. For now, I'm just registering the idea, but I can help to implement it, on future free times :)

Completely agree, timeouts are a standard across other mediums, don't see why they shouldn't be included in this fashion also.

**Comment by hal0x2328** [comment]
Congestion issues probably largely solved by mempool changes since this issue was opened.  But leaving as discussion to raise awareness of the value of the idea in general.
