### ISSUE TITLE
Break when minify with version 4.0.2 and reactJS

### ISSUE THREAD

**Issue by thphu** [CityOfZion/neon-js#312]
Hi,

I'm using your library (version 4.0.2) with reactJS. Everything seem fine with development mode. But When I run `yarn run build` it was raised an error. I also attached the screen shot. Then I get back to version 3.9.2 everything is ok to run `yarn run build`

![image](https://user-images.githubusercontent.com/7285771/45411939-bc4cb880-b69f-11e8-9661-dbbf9c74acb0.png)

**Comment by snowypowers** [comment]
Do you have a simple reproducable repo example?

**Comment by thphu** [comment]
hi @snowypowers  sorry for late response.

You can check my example repo https://github.com/thphu/testingNeo 
When you run with development mode (`yarn start`) everything is ok, but when you compile to deploy (`yarn run build`) there is a error happen.

**Comment by snowypowers** [comment]
the core problem is that create react app doesnt transpile code and it doesn't accept ES6 code. You have a few options:
1. Fork and transpile it yourself.
2. Eject and add a babel step in your production step
3. Submit a PR 
4. Wait for me
5. Wait for create react app to release v2 (which should have support for transpilation)
6. use neon v3 which is published in ES5

Changing output to ES5 is not high on my list as ES6 is already very mainstream for about a year.

**Comment by snowypowers** [comment]
Yes I am aware. Sorry for the trouble.
