### ISSUE TITLE
ERROR: wallet.Wallet.readFile is not a function

### ISSUE THREAD

**Issue by gairom** [CityOfZion/neon-js#317]
Hi,
I upgraded to v4 from 3.7.2 and now I get this error when trying to read a wallet from JSON file.
is 'readFile' method is depracated?  Is there alternative method?
The docs didn't change...  the example from the docs doesn't work:
const w2 = wallet.Wallet.readFile("mywallet.json");

Thanks.

EDIT: I checked and the readFile method was exist until 3.11 but it doesn't in v4.

**Comment by snowypowers** [comment]
Sorry I missed out on updating that. Yes, `readFile` is removed in v4. The alternative is to just read the file yourself using whatever file utility you like and create a new instance:

```
const walletData = fs.readFileSync(filepath)
const wallet = new wallet.Wallet(walletData)
```

This change makes the package more streamlined for both node and browser platforms.

I apologize for outdated docs and will update the changelogs and docs accordingly.

**Comment by gairom** [comment]
Sure, no problem, I understand.
