### ISSUE TITLE
getInputData does not use all available funds

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neon-js#32]
https://github.com/CityOfZion/neon-js/blob/df77a670a961208f8a5c3b73fbfc814b571a33de/src/transactions.js#L102-L107

Take the above code and set `orderedCoins` to (biggest first)
```
            {
                index: 0,
                txid: '1fe78a9a89c72e2a296b0476a3801ae0f3a10c88e74f14236fd522d7af72832c',
                value: 10.0
            },
            {
                index: 1,
                txid: '88e873ce8e8fb00f446ded8eb82521cc7c4285973d950f5112630598b09b1bbd',
                value: 4.0
            }
```
Say we wish to transfer `12` units of some asset. `amount` will be `12`. According to our funds we have `14`in total available. The current implementation will return only 1 input for a total amount of 10, while needing both to be able to reach 12.

First round: 
10 <= 12   (true)
`amount` = is 12-10 = 2

Round 2:
4 <= 2 (false)

**Loop ends**  

We now only add 1 input for a total amount of 10, where we requested 12 and we _do_ have the funds for it.

**Comment by Ejhfast** [comment]
So, before start:
`k = 0`

Then after checking `10 <= 12`:
`k=1`

Then after checking `4 <= 2`:
Loop is broken and `k = 1`

So two inputs will be sent?

**Comment by ixje** [comment]
Long day, you're right.
