### ISSUE TITLE
Document is out of date

### ISSUE THREAD

**Issue by bachvtuan** [CityOfZion/neon-js#321]
The code at this section https://cityofzion.io/neon-js/docs/en/api/core/tx.html#classes is totally out of date and code is not usable.

**Comment by bachvtuan** [comment]
Is it up to date ?

**Comment by yakjunxiang** [comment]
Not deployed at the moment

**Comment by bachvtuan** [comment]
If so why do you close this issue without any explanation ?

**Comment by snowypowers** [comment]
Sorry was commenting on the wrong account.

Anyway if you are awaiting the updates, please just reopen the issue. I was clearing out issues.

**Comment by bachvtuan** [comment]
No problem. I just curious what happened!
