### ISSUE TITLE
Create function bigEndianToLittleEndian

### ISSUE THREAD

**Issue by igormcoelho** [CityOfZion/neon-js#322]
Guys, in a recent discussion at https://github.com/neo-project/neo-vm/issues/17 I found out many people (including me) are still confused with endianess at neo... perhaps the community itself is not helping to enforce the standards, so that causes problems.

My suggestion is to create functions `bigEndianToLittleEndian` and `littleEndianToBigEndian`, which are virtually the same as `revertHex` function. The only difference is that, according to Neo, big endian should start with `0x` (and little endian does not). 

So, for example, the `revertHex` function below should be replaced by `bigEndianToLittleEndian`, and this function must guarantee that input scripthash is passed like `0x68ebfc4fefbe24c9cff0f7e3c0d27ed396d07f9f`, and the output is after `bigEndianToLittleEndian` is `9f7fd096d37ed2c0e3f7f0cfc924beef4ffceb68` (without 0x).
https://github.com/CityOfZion/neon-js/blob/31600a3cb9c38b9a0d961e98475e4cc81c908cd8/packages/neon-core/src/wallet/core.ts#L106-L112

On the other hand, function `littleEndianToBigEndian` applied to `9f7fd096d37ed2c0e3f7f0cfc924beef4ffceb68` should return `0x68ebfc4fefbe24c9cff0f7e3c0d27ed396d07f9f`, enforcing big endian 0x format.

**Comment by snowypowers** [comment]
Im up for this if it is clear that this is a common standard that we can agree on throughout the NEO eco system. Im not clear on the impact at the moment as this might introduce some breaking changes (some functions will need to understand the `0x` prefix).

**Comment by hal0x2328** [comment]
Setting as discussion until decision reached on viability and potential impact.
