### ISSUE TITLE
handle change when spending partial UTXO

### ISSUE THREAD

**Issue by gairom** [CityOfZion/neon-js#325]
Hi,
I have a question regarding partial UTXO spend, since UTXO can be only spent once the unspent balance needs to be handled (I'm manually building and signing the transaction and send it to the rpc node with 'sendrawtransaction').
As far as I understand I should transfer it to myself (assuming I have one address).
Is there any way to manage it by neon-js or I need to create another transaction to transfer it to myself?
If so, I assume I need to use 'sendmany' method since I won't be able to do it in 2 different transactions if the UTXO has been already spent by the first...

Can anyone please advise what's the best approach to handle it?
Thanks.

Edit: I just saw that rpc method 'sendmany' requires to open the wallat on the node so that's not an option...
I see when there's no change (transaction amount matches UTXO) there's one output and when there's a change there are 2 outputs, however, how can I know the txid of the change going back to the address in order to make it available as UTXO for future transaction?

**Comment by snowypowers** [comment]
The calculation methods will determine the leftover assets after all intents have been met and deposit them back to the originating account. Most of the code assumes a single source of assets (coming from a single address) so it will always return leftovers back to the same address.

Please experiment with a private net. This answer is easily answered with a simple test.

Please move such questions to discord as they are system questions than technical issues of the project.
