### ISSUE TITLE
[FEATURE] NeoNameService implementation

### ISSUE THREAD

**Issue by merl111** [CityOfZion/neon-js#327]
The release of NNS brings names to the NEO blockchain. I think it would come really hand to have a simple implementation which allows others to use the NEL API methods (and other APIs connecting to the name service contracts) to easily lookup domains or do reverse lookups.

Beside that also API calls for domain auctions could be implemented and things like the ownership transfer of domains to have easy access to those too. 

My suggestion would be to create a new package similar to neon-api, maybe called neon-ns dedicated to naming services (lookup, auctions, domain management), with it's own providers with a minimal set of method calls and extended providers for more specific things.

Maybe somebody has a different idea or would like to add something?

**Comment by nickfujita** [comment]
The following PR adds the base use case of domain name resolution from a direct contract call, and is packaged into it's own plugin.

https://github.com/CityOfZion/neon-js/pull/328

**Comment by snowypowers** [comment]
Closed by #337
