### ISSUE TITLE
building a transaction

### ISSUE THREAD

**Issue by Marxpark** [CityOfZion/neon-js#332]
I'm trying to build and send a transaction from a multisig account i've created. The multisignature account works fine and i've transfered some gas to it, but building a transaction for it fails at addINput.

```
const api = require('@cityofzion/neon-js').api
const Neon = require('@cityofzion/neon-js').default
const {tx, rpc} = require('@cityofzion/neon-js')

const testNetNeoscan = new api.neoscan.instance("TestNet");

const signer1 = new wallet.Account("89f20852b451366f30f7254f5d42f0876e408b8a601afd5a88cd638e1e2ee8cb");
const signer3 = new wallet.Account("119b3379f5cada518c9cab569c389482b4dea20ffde1854f648fc0979934c0ea");
const verificationScript = "52210319e6633074693e063a1bcfd9372a02d9e6016a7cd7aae42ee898b7909ff89ef921027fcceaa6fe25194b03135f0bf886ec9951f393a7084260dafbca65d70d0259942102b612a907d9f9d5e90e49f736971b0b05405fbc9b1c04043285250015dd883ad953ae"
const testNetRpc = new rpc.RPCClient("https://test4.cityofzion.io:443");

testNetNeoscan.getBalance('ANffKR2qqK3VyY34f3aQEuufVEZJbAaGxR').then((result) => {
    console.log(result.assets.GAS.unspent[0].value.c)

    let trnas = Neon.create.contractTx();
    trnas.addOutput("NEO", 2, "AQ9GeL84C8P4XwgejrPBZoYdvgRLZyxKM9")
    .addRemark("I am sending 2 GAS to AQ9GeL84C8P4XwgejrPBZoYdvgRLZyxKM9") // Add an remark
    .calculate(result) // Now we add in the balance we retrieve from an external API and calculate the required inputs.
    let serializedTx = trnas.serialize();

    let signature1 = wallet.sign(serializedTx, signer1)
    let signature3 = wallet.sign(serializedTx, signer3)

    let witness = tx.Witness.buildMultiSig(
        serializedTx,
        [signature1, signature3],
        verificationScript
      );

    serializedTx.scripts.push(witness);
    testNetRpc.sendRawTransaction(serializedTx);

}).catch(err => {
    logger.error(err)
});
```

This keeps giving me the error
error:   TransactionOutput requires assetId, value and scriptHash fields.
I dont understand why and as far as i have studied all the various documentations (which aren't very consistent... ) i think that i'm not doing anything wrong. I've also tried replacing the address (in the addOutput(...args)) with the scripthash of the account (0x45bacdd9dbf2aa9b4b5f6d2ba09cab9540f0cc5b) but i get the same error.

Am i doing something wrong? What should i do, and are there other optimizations that i can make with this code? 

Thank you for your help, M.

**Comment by Marxpark** [comment]
I've managed to get around it using this
`trnas.addOutput({assetId: "NEO", value: 2, scriptHash: "AQ9GeL84C8P4XwgejrPBZoYdvgRLZyxKM9"})`

but now i'm getting errors for NEO / neo / GAS / gas / NEOGas error:   Expected a hexstring but got NEO. If i put in the hexstring for the assets ("0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b" for NEO for example, not sure if its even right) i get error:   This balance does not contain any undefined!.

I managed to get error:   This balance does not contain any NEO! once, then sent some NEO to the address and now i cant recreate it.

**Comment by Marxpark** [comment]
I now got past yesterdays error using 
`trnas.addOutput({assetId: "c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b", value: 2, scriptHash: "45bacdd9dbf2aa9b4b5f6d2ba09cab9540f0cc5b"})`

So i use hex strings for the asset id and the scriptHash of the recipient. This isn't the most convenient and any help or clarification would be very appreciated :) .

Now that i dont get an error at the adding input, the code produces something less verbose: 
error:   Assertion failed 
I'm not sure where exactly this happens and which assertion fails. 

Thanks for any help in advance :D

**Comment by Marxpark** [comment]
Assertion failed issue resolved by passing in private key as string instead of an account. I seen to have mixed up the advanced signing guides "Using objects" and "Using hexstrings" for this part. 

New problem is when i try to push the witness to the transaction scripts
`error:   TypeError: Cannot read property 'push' of undefined` 
Looking into it now. 

It's still confusing that i have to pass an object to the addOutput function and that the values for asset id and recipient address have to be hex instead of regular addresses. The documentation should be updated, or my faulty code should be repaired, if it has something to do with what I did.

**Comment by Marxpark** [comment]
I managed to get everything "working" with the following code 
```
const testNetNeoscan = new api.neoscan.instance("TestNet");
const verificationScript = "52210319e6633074693e063a1bcfd9372a02d9e6016a7cd7aae42ee898b7909ff89ef921027fcceaa6fe25194b03135f0bf886ec9951f393a7084260dafbca65d70d0259942102b612a907d9f9d5e90e49f736971b0b05405fbc9b1c04043285250015dd883ad953ae"
const testNetRpc = new rpc.RPCClient("https://test4.cityofzion.io:443");

testNetNeoscan.getBalance('ANffKR2qqK3VyY34f3aQEuufVEZJbAaGxR').then((result) => {

    let trans = Neon.create.contractTx();
    trans.addOutput({assetId: "c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b", value: 2, scriptHash: "45bacdd9dbf2aa9b4b5f6d2ba09cab9540f0cc5b"})
    .addRemark("I am sending 2 NEO to AQ9GeL84C8P4XwgejrPBZoYdvgRLZyxKM9") 
    .calculate(result) 
    let serializedTx = trans.serialize();

    let signature1 = wallet.sign(serializedTx, "89f20852b451366f30f7254f5d42f0876e408b8a601afd5a88cd638e1e2ee8cb")
    let signature3 = wallet.sign(serializedTx, "119b3379f5cada518c9cab569c389482b4dea20ffde1854f648fc0979934c0ea")

    let witness = tx.Witness.buildMultiSig(
        serializedTx,
        [signature1, signature3],
        verificationScript
      );
    
    trans.scripts.push(witness);
    serializedTx = trans.serialize();
    testNetRpc.sendRawTransaction(serializedTx).then((result) => {
        console.log(trans.hash);
        console.log(result)
        console.log("maybe success... maybe");
    }).catch(err => {
        console.log(err.stack)
    })
    

}).catch(err => {
    logger.error(err.stack)
});
```

I'm confident that i'm using the right private keys for the multisig account, i can post all of the keypairs and how i generated the multisig, but this transaction fails to be broadcasted. The result in the last block is always false.

**Comment by Marxpark** [comment]
I got it working. The last thing that were a couple of false and true flags at the serialisation function (this should be added to the documentation, currently it's only in the source code). Transactions made and like this can be sent with the sendRawTransaction command. 
```
    let trans = Neon.create.contractTx();
    trans.addOutput({assetId: gasId, value: 2, scriptHash: "45bacdd9dbf2aa9b4b5f6d2ba09cab9540f0cc5b"})
    .addRemark("I am sending 2 GAS to AQ9GeL84C8P4XwgejrPBZoYdvgRLZyxKM9") 
    .calculate(result);
    let serializedTx = trans.serialize(false);

    let signature1 = wallet.sign(serializedTx, "L1qrmDqgy5kF9DrKWYKa1sGW5jBy5bxcvv3kMSyHY9CKJridmT6P")
    let signature3 = wallet.sign(serializedTx, "KwowC4TQbzrYRmJMkC5VisB6fcLrNgj9Rj7teMEooQ38y5iQCRnH")

    let witness = tx.Witness.buildMultiSig(
        serializedTx,
        [signature1, signature3],
        verificationScript
      );
    
    trans.scripts.push(witness);

    serializedTx = trans.serialize(true);

```

Hope this helps someone else as well. I would still like to know which parts of my code can be improved and if there's a way to pass normal assetIds and Addresses to the addOutput function.

Thanks.

**Comment by snowypowers** [comment]
You should look at `addIntent` if you want to use symbols and addresses.

The hexstrings you are using have `0x` appended in front which are actually not part of the hexstring itself. You need to remove the `0x` for it to be a valid hexstring in neon-js.

The serialisation function is documented in the source code and done so only because it is difficult to maintain accuracy in the documentation (as you can tell with the holes you have discovered).

I would appreciate it if you can fix up some of the documentation bugs you notice while doing this!
