### ISSUE TITLE
Wrong BigInteger conversion

### ISSUE THREAD

**Issue by belane** [CityOfZion/neon-js#345]
It seems that there is an error in the BigInteger conversion, the following example shows the issue.
```js
function1 = async (address, label, value, balance) => {
    const script = this.buildScript('run', [
      string('function'),
      byteArray(address, 'address'),
      string(label),
      integer(value)
    ]);

    return this.invoke({ script, balance });
  };
```
When I run function1 with these parameters; `AddressXXXX...`, `'label'`, `14256661` it generates the following script code.
```
PUSHBYTES3: 0x158ad9 --> 14256661 (wrong)
PUSHBYTES5: 0x6c6162656c --> label
PUSHBYTES20: 0xXXXXX... --> AddressXXXX...
PUSHBYTES8: 0x66756e6374696f6e --> function
PUSH4 PACK
PUSHBYTES3: 0x72756e --> run
APPCALL: xxxx... --> contract_address
```

The problem is `14256661` has been converted to `0x158ad9` what is not `14256661` , is -`2520555` in BigInteger and since VM interprets values as BigInteger, the conversion is wrong.
The right value for `14256661` is `158ad900`

Here a C# example of the right conversions for `14256661` https://dotnetfiddle.net/IfHgvp

**Comment by snowypowers** [comment]
OK so C# BigInteger uses twos complement that explains the weird conversion. I understand how it works, maybe its time to bring in the csbiginteger package that igor has made.
