### ISSUE TITLE
TypeScript typings have no default export

### ISSUE THREAD

**Issue by rockacola** [CityOfZion/neon-js#349]
Replicated version:

* `3.11.0`
* `4.1.3`

Error message when attempts to build a TypeScript project that uses `neon-js`

```js
node_modules/@cityofzion/neon-core/lib/logging.d.ts:1:8 - error TS1192: Module '"/Users/travis/ProjectGit/rockacola/neo-js/node_modules/@types/loglevel/index"' has no default export.

1 import loglevel from "loglevel";
         ~~~~~~~~

node_modules/@cityofzion/neon-core/typings/elliptic.d.ts:2:10 - error TS1192: Module '"/Users/travis/ProjectGit/rockacola/neo-js/node_modules/@types/bn.js/index"' has no default export.

2   import BN from "bn.js";
```

**Comment by rockacola** [comment]
Unable to replicate the said concern in following versions:

* `3.10.0`
* `3.10.1`

**Comment by snowypowers** [comment]
Do you have a simple repro project available. Im somehow unable to repro it easily...

**Comment by rockacola** [comment]
Sure

* Clone https://github.com/CityOfZion/neo-js, `master` branch
* Noticed that the `package.json` is currently reference to `"@cityofzion/neon-js": "3.10.0"`.
  * Execute `npm run rebuild`, which should setup `node_modules` and execute TypeScript compiler on `neo-js` project.
  * You are to expect `npm run rebuild` to complete without error messages.
* Now, manually update the `package.json` to point to a version of concern
  * say, `"@cityofzion/neon-js": "3.11.0"`
  * Execute `npm run rebuild` will refresh `node_modules` and execute TypeScript compiler on `neo-js` project.
  * You are expect to see the said error messages coming from TypeScript compiler.

**Comment by snowypowers** [comment]
Im unable to see this with v3.11.6, which is weird considering i did not touch the typings for that from 3.11.0 to 3.11.6. Gets a little harder to test this out with v4 but I will test it more tomorrow.

**Comment by snowypowers** [comment]
I dug more into this and realise this is an ES6 vs CJS import issue. This is because of how typescript modules are coupled tightly to ES6 modules but the modules we are consuming are CJS modules, resulting in a breakage of types. You will have to enable `esModuleInterop` in your `tsconfig.json` and your `tsc` should pass in neo-js.

**Comment by rockacola** [comment]
@snowypowers awesome finding. Thank you very much for the pointer and confirmed said changes rectify the issue.

**Comment by rockacola** [comment]
Closing ticket as it is no longer believed to be a concern of neon-js
