### ISSUE TITLE
Implementation parsing of all Transaction types

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neon-js#357]
Currently, neon-js is only able to parse the most heavily used transaction types. We want to achieve full transaction support so we are able to present any transaction in a proper JSON format.

**Comment by dauTT** [comment]
Hi @snowypowers ,
Can I work on this task?

It seems to me that there are still 5 transactions type to parse. Correct?

| Transaction Type | Parsing Status| 
| ------------- | ------------- |
|MinerTransaction | **Open** |
 | IssueTransaction | **Open** |
 | ClaimTransaction | Done |
  |EnrollmentTransaction | **Open** |
  |RegisterTransaction | **Open** |
  |ContractTransaction | Done |
  |StateTransaction | Done |
  |PublishTransaction | **Open** |
  |InvocationTransaction | Done|

**Comment by snowypowers** [comment]
sure. Do try to open individual PRs for each type so its easier to review.

**Comment by dauTT** [comment]
@snowypowers ,

Enrollment, Register and and Publish  transactions are marked as obsolete. Do you still want to parse them?

https://github.com/neo-project/neo/blob/master/neo/Network/P2P/Payloads/EnrollmentTransaction.cs#L13

https://github.com/neo-project/neo/blob/master/neo/Network/P2P/Payloads/RegisterTransaction.cs

https://github.com/neo-project/neo/blob/master/neo/Network/P2P/Payloads/PublishTransaction.cs

**Comment by snowypowers** [comment]
yes. Even when deprecated, the transactions still exist on the blockchain, we just should not send in any new ones. Currently, neon-js will throw an error when encountering such transactions. We should have the ability to at least deserialize and view the transaction.

**Comment by dauTT** [comment]
All task completed. @snowypowers , we can close this issue.
