### ISSUE TITLE
sign tx with ledger for multi-sign address

### ISSUE THREAD

**Issue by MickWang** [CityOfZion/neon-js#362]
I refer to this doc http://cityofzion.io/neon-js/docs/en/guides/adv/multisig.html to add signatures for transaction. The transaction is to send NEO from multi-sign address. But i got error here:
```
const witness = tx.Witness.buildMultiSig(
  hex,
  [signature1, signature2],
  verificationScript
);
unsignedTx.scripts.push(witness);
```
> TypeError: Cannot read property 'buildMultiSig' of undefined

The signature is from ledger so there is no Witness in the tx object.
Please help me with this situation. Thanks a lot.

**Comment by snowypowers** [comment]
`tx.Witness.buildMultSig` is a static method. It does not live with the transaction instance. `tx` here refers to the imported module.

**Comment by MickWang** [comment]
Hi,  I use this method to create the tx.
```
const tx = Neon.create.contractTx();
```
I already get the signatures and how can i put the signatures into the tx. 
If `tx.Witness.buildMultSig` is a static method and how the error happended?
Thanks.

**Comment by corck** [comment]
tx refers to the imported `tx`, not the transaction instance. 
so you need to do something like
```
import { wallet, tx, u } from "@cityofzion/neon-js";
const transaction = Neon.create.contractTx();
tx.Witness.buildMultiSig(....
```

**Comment by MickWang** [comment]
Thank you all. It works.
