### ISSUE TITLE
Deserializing the transaction fails

### ISSUE THREAD

**Issue by corck** [CityOfZion/neon-js#366]
Seems like the transaction deserialization is broken in 4.2.0. For testing reasons I've added the deserialize function into the signingFunction callback.

Might be related to #348 but as my Array is not empty I'm not sure.

```
  async signTransaction() {
    let account = Neon.create.account("0241d9c83dbce267b022e6316345092dddf318298350722f935961d8fb17c67c38")
    console.log(account)
    const privateNet = new rpc.Network(ENV.APP.neoConfig.networkConfig)
    Neon.add.network(privateNet)
    const config = {
      api: new api.neoscan.instance('PrivateNet'),
      script: Neon.create.script({
        scriptHash: this.get('contractScript'),
        operation: 'mintTokens',
        args: [1000]
      }),
      account: account,
      signingFunction: this.signTx,
      gas: 1
    },

    Neon.doInvoke(config).then(res => {
      console.log(res);
    }).catch(err => {
      console.error(err)
    });
  },

    signTx(trx, publicKey) {
      console.log("Signing", trx, publicKey)
      tx.Transaction.deserialize(trx) // throws error
    }
```

`tx.Transaction.deserialize(trx)` fails with:
```
 sign-transactions.js:96 Error: Reached the end of the stream!
    at StringStream.read (StringStream.js:45)
    at StringStream.readVarInt (StringStream.js:63)
    at deserializeArrayOf (main.js:32)
    at Object.deserializeWitnesses (main.js:26)
    at Function.deserialize (Transaction.js:27)
    at Object.signTx [as signingFunction] (sign-transactions.js:102)
    at eval (sign.js:16)
    at Generator.next (<anonymous>)
    at eval (sign.js:2)
    at new Promise (<anonymous>)
```

**Comment by snowypowers** [comment]
Do you have the string that was being deserialized?

**Comment by corck** [comment]
Sure
`d1012502e80351c10a6d696e74546f6b656e73676c3f26d7b3a8b2079d053ceb86d13a2fe42b402900e1f5050000000000016ee3ab02e4b1955e38e5e3a8219887bfe62431ed1e476559875e59609d6e85c4000001e72d286979ee6cb1b7e65dfddfb2e384100b8d148e7758de42e4168b71792c60f035e0d90b000000f00cf8e363c29f33f8333df8462d06cae499b5fa`

**Comment by corck** [comment]
Hm, we got one step further, but now it fails with `Error: Unknown TransactionType`

**Comment by snowypowers** [comment]
so it looks like something went wrong with the production version. The dev version seems to be working fine. I will get another version out in a few days time.

**Comment by corck** [comment]
Ok, will monitor. Would be great to get it working. Then I can hopefully use my Ledgers for invoking smart contracts.

**Comment by snowypowers** [comment]
@corck I just published a new patch. Please try it out.

**Comment by corck** [comment]
@snowypowers thx, it's working now!
