### ISSUE TITLE
[error] Some contracts to be deployed are failling

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neon-js#377]
Since version 4.x.x something happen and some contracts are returning errors when tried to be deployed, for example, the ICO template.

I need to investigate with careful.
I am still not sure if it is something related to the `ScriptBuilder` or `Neon.default.create.contractParam` or something else.

**Comment by snowypowers** [comment]
You will need to check if the generated script is any different. If it is intermittent with the same script, that suggests more of network / UTXO issues. If you can capture the outgoing transactions and compare between a successful and failed one then would be helpful.

**Comment by vncoelho** [comment]
Did anything change with:
```js
Neon.default.create.contractParam('Integer', Number(value))
Neon.default.create.contractParam('ByteArray', negbigint2behex(value))
Neon.sc.ContractParam.byteArray(value, 'fixed8')
Neon.default.create.contractParam('ByteArray', value)
Neon.sc.ContractParam.byteArray(value, 'address')
```

**Comment by vncoelho** [comment]
@snowypowers, the error was discovered by @igormcoelho  and it was the lack of attacking network fee, which cause some contracts with bigger size to fault.
