### ISSUE TITLE
unable to install neon-js via yarn and commit hash

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-js#381]
When trying to install neon-js with yarn and specifying a branch, tag, commit etc the installation fails with `error Can't add "neon-js": invalid package version undefined.` because `package.json` is missing the version key. 

If we add a version at `./package.json` users will not have this issue

**Comment by snowypowers** [comment]
are you trying to install with hash? Can you provide an example because I can install with version tag.

Not sure if adding the version tag at the root `package.json` will help due to the mono repo style.

**Comment by comountainclimber** [comment]
Sorry for not being more specific an example would be `"neon-js": "git+https://github.com/cityofzion/neon-js.git#3.11.0"` or  `"neon-js": "git+https://github.com/cityofzion/neon-js.git#129b883fa6aff2df9b965b689886fe754d5c4800"`

**Comment by snowypowers** [comment]
That will not work with the mono repo setup, the url points to the root of the mono repo and it is unable to find its way into the packages. You have to depend on npm instead of direct urls.
