### ISSUE TITLE
Add support for Serialization/Deserialization of NEO arrays and dicts

### ISSUE THREAD

**Issue by saltyskip** [CityOfZion/neon-js#393]
Currently NEO has an internal format for serializing and deserializing dictionaries and arrays into byte arrays. As shown below

https://github.com/neo-project/neo/blob/5894cbd7c24c12fb7d181c134bfe1e7d3664e2e4/neo/SmartContract/StateReader.cs#L354

It is expected that smart contracts will return these serialized byte arrays when returning a dictionary or byteArray.

EG
https://github.com/Splyse/neo-nft-template/blob/master/nft_template.py#L235

It would be good to create a function in neon-js so that we can deserialize/serialize these byte arrays into the expected NEO format. Otherwise a custom parser will have to be built by each application.

**Comment by ediopia** [comment]
I use sc.StackItem.deserialize to deserialize returns from our smart contract.

**Comment by saltyskip** [comment]
Hi Ed, 

Thank you, that's exactly what I was looking for

Cheers 👍
