### ISSUE TITLE
[feature] support for neo-cli rpc utxo tracking

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neon-js#395]
Dear @snowypowers,

as we were discussing, an upcoming PR will be soon merged into Neo official plugins: https://github.com/neo-project/neo-plugins/pull/52

It sounds interesting that neon-js supports UTXO and Claims api query direct from neo-cli nodes.

Basically, it involves 3 apis: getunspents, getunclaimable and getclaimable.

**Comment by jsolman** [comment]
3 rpc operations: `getunspents`, `getclaimable`, and `getunclaimed`.

The response formats will match neoscan response format.

**Comment by vncoelho** [comment]
Result of getunclaimed
![image](https://user-images.githubusercontent.com/17395762/54314382-48418d80-45ba-11e9-87ef-5d32f4f6f167.png)

![image](https://user-images.githubusercontent.com/17395762/54314493-96569100-45ba-11e9-975d-5ec3280f8d8b.png)

available is the sum of all spent utxos that contains claim
unavailable is the sum of all unspent utxos
unclaimed is the total

**Comment by vncoelho** [comment]
result of getclaimable

![image](https://user-images.githubusercontent.com/17395762/54314522-ac645180-45ba-11e9-90d6-a4dd12886998.png)

**Comment by vncoelho** [comment]
Result of { "jsonrpc": "2.0", "id": 5, "method": "getunspents", "params": ["AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y"] }

```js
{
  "jsonrpc": "2.0",
  "id": 5,
  "result": {
    "balance": [
      {
        "unspent": [
          {
            "txid": "5ba260d2859ef3194471bcbe8549a044211d2dd900da20ad604df9507e6e738c",
            "n": 0,
            "value": 1464
          },
          {
            "txid": "34a3b3e6c7e7e60291ea0e2f24ab7ab86d966fa7de1b3aeb054626c63545c48f",
            "n": 0,
            "value": 384
          }
        ],
        "asset_hash": "602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7",
        "asset": "GAS",
        "asset_symbol": "GAS",
        "amount": 1848
      },
      {
        "unspent": [
          {
            "txid": "94f11dd277dd48cf1fccef8c02664adacdd9890410aaed8ddb01535433b3fc41",
            "n": 0,
            "value": 100000000
          }
        ],
        "asset_hash": "c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b",
        "asset": "NEO",
        "asset_symbol": "NEO",
        "amount": 100000000
      }
    ],
    "address": "AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y"
  }
}
```

**Comment by vncoelho** [comment]
It is now online at https://neocompiler.io/ if you want to try the RPC apis.

**Comment by vncoelho** [comment]
Thanks for the agility and great work, @snowypowers!
