### ISSUE TITLE
Redirecting neon-js.readthedocs.org to cityofzion.io/neon-js

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-js#406]
The old readthedocs.org site is still linked to from Google and elsewhere, even though the newer Docusaurus site is now the canonical documentation site for neon-js. This may lead to developer confusion since the readthedocs documentation is out-of-date now with the last update over a year ago.

Rather than simply delete the deprecated documentation site, it would be better to redirect the individual pages to their corresponding replacements on cityofzion.io/neon-js/ for a seamless transition. readthedocs supports redirects of this sort, but *only* if the existing documentation page returns `404 not found`.

Even though the old readthedocs build information has been removed from the neon-js repo, this doesn't cause the documents to disappear from the readthedocs site - instead it simply delivers the last known good build of the documentation, forever. So redirects won't work unless we make a change to the neon-js repo that results in a new successful Sphinx documents build.

I think the best way to do this is to create a new branch of neon-js and create an empty readthedocs Sphinx configuration, with a single index page telling users the documentation has moved to cityofzion.io/neon-js/.

Then we need to change the readthedocs configuration to pull the documentation build files from this branch instead of dev or master, then do a manual build on readthedocs.org. This should leave the `/en/latest` tree on readthedocs empty except for the new index file. And now all of the old sub-documents should return a 404 error.

Then we just need to add redirects to cityofzion.io/neon-js/ in the readthedocs project admin panel for all the sub-documents.

I have a live example of how this should work that can be tested here:

https://splyse-neon-js-docs.readthedocs.io/en/latest/

This was built from this Github branch:

https://github.com/Splyse/neon-js/tree/readthedocs/docs

And I added a redirect for:

https://splyse-neon-js-docs.readthedocs.io/en/latest/rpc/ 

which automatically sends the browser to:

http://cityofzion.io/neon-js/docs/en/api/core/rpc.html

If no one has any objections, I will add this branch to neon-js, then I just need @Ejhfast to add me as an administrator on neon-js.readthedocs.io and I will handle setting up the all of the redirects.

**Comment by snowypowers** [comment]
I do think its a good idea to remove the outdated docs. Unfortunately, I do not have the keys so you will need @Ejhfast to move forward.

**Comment by hal0x2328** [comment]
@Ejhfast here are the redirects that should be added to the readthedocs control panel once the neon-js branch with the empty document tree is added to both Github and readthedocs.

/en/latest/rpc/ -> https://cityofzion.io/neon-js/docs/en/api/core/rpc.html
/en/latest/transactions/ -> https://cityofzion.io/neon-js/docs/en/api/core/tx.html
/en/latest/smart_contracts/ -> https://cityofzion.io/neon-js/docs/en/api/core/sc.html
/en/latest/light_wallet_api/ -> https://cityofzion.io/neon-js/docs/en/api/index.html
/en/latest/wallet.html -> https://cityofzion.io/neon-js/docs/en/api/core/wallet.html
/en/latest/installation.html -> https://cityofzion.io/neon-js/docs/en/installation.html
/en/latest/overview.html -> https://cityofzion.io/neon-js/docs/en/overview.html
/en/latest/reference/wallet.html -> https://cityofzion.io/neon-js/docs/en/api/core/wallet.html
/en/latest/reference/rpc.html -> https://cityofzion.io/neon-js/docs/en/api/core/rpc.html
/en/latest/transactions/claim.html -> https://cityofzion.io/neon-js/docs/en/guides/basic/claimgas.html
/en/latest/transactions/invoke.html -> https://cityofzion.io/neon-js/docs/en/guides/basic/invoke.html
/en/latest/reference/index.html -> https://cityofzion.io/neon-js/docs/en/api/index.html
/en/latest/transactions/contract.html -> https://cityofzion.io/neon-js/docs/en/api/core/sc.html

**Comment by hal0x2328** [comment]
Added new `readthedocs` branch with an empty config to the neon-js repo, so that can now be added as the default branch for the `latest` readthedocs config to pull from, which should delete all the outdated docs as soon as it is rebuilt. Then once they are added, the absolute redirects above will take over.

**Comment by Ejhfast** [comment]
@hal0x2328 I can give you readthedocs admin privileges. can you create an account there and tell me the username?

**Comment by hal0x2328** [comment]
@Ejhfast Yes, it's hal0x2328 there too.

**Comment by Ejhfast** [comment]
Done!

**Comment by hal0x2328** [comment]
Ok, the new empty docs build worked, all that is left on the readthedocs.io/en/latest site is a message pointing users to the new documents repository. All the sub-pages for specific API information are automatically redirecting to the closest matching page on the cityofzion.io site.
