### ISSUE TITLE
Add JSFiddle examples to documentation

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-js#413]
@phetter has prepared a large number of JSFiddle neon-js examples that can be embedded into the docs, with more on the way.

JSFiddle lets you pull example code directly from Github so you don't have to maintain demo code on two different sites.

So this folder would become part of the neon-js repo:
https://github.com/phetter/neon-js/tree/master/examples/browser

And then individual example JSFiddles can be directly referenced/embedded with no additional work required, e.g.:

https://jsfiddle.net/gh/get/jquery/3.0/phetter/neon-js/tree/master/examples/browser/doinvoke/demo

However, these only work with his forked build of neon-js that contains the recent `httpsOnly` fix. Before adding these examples to the neon-js docs we really should have them all pulling the official release library instead of a fork.

So we need a new neon-js release to proceed adding the first batch of examples. @snowypowers

**Comment by snowypowers** [comment]
please try v4.5.2 and let me know if there are any issues.
