### ISSUE TITLE
There is no dist/index.js file in neon-js package v4.5.0

### ISSUE THREAD

**Issue by alexkvak** [CityOfZion/neon-js#418]
There is no dist/index.js file in neon-js package v4.5.0

```
# ls node_modules/@cityofzion/neon-js/dist
browser.js        
browser.js.map    
index.d.ts        
index.d.ts.map    
networks.d.ts     
networks.d.ts.map
```

**Comment by snowypowers** [comment]
@alexkvak I have published 4.5.2 which I have ensured the artifacts are there. Thanks for raising the issue. The core problem seems to be wonky behavior by the clean-webpack-plugin which manages to wipe out the browser.js when ran in dev or index.js when ran in prod.
