### ISSUE TITLE
Creating wallet from publicKey is not working properly

### ISSUE THREAD

**Issue by mmo2112** [CityOfZion/neon-js#427]
Hi there, I use HDPrivateKey from bitcore-lib to contain my privateKey. The simple way is HDPrivateKey -> ExtendHDPrivateKey with derive path (optional or not declaring anything else) -> privateKey -> publicKey. The problem I've got stuck is creating address from publicKey not working properly. Example I have 2 HDPrivKey, so I may have 2 privateKey but publicKey generated from there can not work well, 1 is not valid input. I try to test with random HDPrivateKey and it's same problem, some of these publicKey is not valid and can not create wallet following example multi.js on git/example. Maybe the problem is different of encode from bitcore-lib/HDKey vs Neon or something other? Thanks so much for an advice.

//
```
const { default: Neon, api, wallet, tx, rpc } = require("@cityofzion/neon-js");
const bitcore = require("bitcore-lib");
var HDPrivateKey = bitcore.HDPrivateKey;
var count_true = 0;
const length_to_test = 10;

for (var i = 0; i < length_to_test; i++) {
    const inputHDPriv = new HDPrivateKey();
    const HDPrivKey = new HDPrivateKey(inputHDPriv);
    const path = "m/0/1/0"; //the path I'm using
    const extendPrivKey = HDPrivKey.derive(path);
    const hdPubKey = extendPrivKey.hdPublicKey;
    const privateKey = extendPrivKey.privateKey.toString("hex");
    const publicKey = hdPubKey.publicKey.toString("hex");

    try {
        const walletFromPub =  new wallet.Account(publicKey);
        console.log("wallet from pub", walletFromPub);
        count_true++;
    }
    catch (error) {
        //throw new Error(error.toString());
        console.log(privateKey.toString("hex") + " error...");
    }
}

console.log("----")
console.log("count true", count_true);
console.log("count false", length_to_test - count_true);
```

**Comment by hal0x2328** [comment]
I think the error is probably due to the bitcore library using the secp256k1 ecc curve, where Neo uses secp256r1.

**Comment by mmo2112** [comment]
> I think the error is probably due to the bitcore library using the secp256k1 ecc curve, where Neo uses secp256r1.

Yeah, because of this problem, I can not create address from some Bitcoin publicKey which is generated from my privateKey (to test multiple address with holding only main privateKey like Bitcoin chain). So I use getScriptHashFromPublicKey, by sending "invalid" Bitcoin publicKey to there and it generate a new one address. But the newer problem is I can not sign those address using that  main privateKey. If I create address directly from privateKey, I still can sign it well. Hm, I'm much at confusing, may you give me some extra advice, thanks for your help so much.

**Comment by mmo2112** [comment]
@hal0x2328,
Hi bro, sorry for disturbing you again. I have both pair private and public secp256k1 and secp256r1. They are same private key but not same public key because of difference between these 2 algorithm. I have read few doc and I think that an unique r1 key pair will be different as k1, and no way to retrieve r1 private key from this k1 private key? I just hope you to confirm me there is no way... cuz it's my mistake when I'm not enough careful to test crypto key, so I will accept loss asset, thanks so much and have a nice day.
