### ISSUE TITLE
Question about MAX_CLAIMS_LENGTH?

### ISSUE THREAD

**Issue by yugasun** [CityOfZion/neon-js#429]
When I create `ClaimTransaction`, I found I has a limit for `claims length`  when init depend on [MAX_CLAIMS_LENGTH](https://github.com/CityOfZion/neon-js/blob/master/packages/neon-core/src/tx/transaction/ClaimTransaction.ts#L74), could you tell me why do this job?

Because of this reason, when create claim transaction and the unclaim tx length is bigger than `255`, we can not pass `claims` to `ClaimTransaction` constructor, then use `addClaims` to init claims output, like below:

```js
import { tx } from '@cityofzion/neon-core';

const tx = new tx.ClaimTransactionn();
tx.addClaims({
    address: 'xxx',
    claims: [], // length bigger than 255
})
```

**Comment by snowypowers** [comment]
This was added quite a long time ago due to some constraints on the neo node side that forces it to be 255 or lower. I can't find the corresponding code so it might have been removed.

**Comment by yugasun** [comment]
@snowypowers So, if my `ClaimTransaction ` contains more than `255` claims, what will it happen to `NEO` node？
