### ISSUE TITLE
[Enhancement] Support enumerator return from contract

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-js#437]
NEP-11 has methods `tokens` and `tokensOfOwner` and `ownerOf` which should return an `enumerator` instead of an array or serialized data. neon-js should provide helper methods to invoke `enumerator`-returning operations more easily.

Currently, if I want to iterate over items returned in an enumerator, I need to build a script by hand to invoke the contract operation and loop with `Iterator.next`, adding each key/value to the stack before the end of the script execution so that they can be read as an array or object by the invoking dApp.

For example, on TestNet I have a contract that has an `enumerate` function to return some example items from storage. In order to build the script to iterate over the results, I wrote the following Python contract:
```
from boa.interop.Neo.App import RegisterAppCall
from boa.interop.Neo.Runtime import Log
from boa.interop.Neo.Iterator import Iterator

enumerate = RegisterAppCall('1e68de2d4442b868c544b4104c8fe2172f580591', 'operation', 'args')

def Main():
    token_iter = enumerate('enumerate',[])
    count = 0
    result = []
    while token_iter.next() and (count < 5):
        result.append(token_iter.Value)
        count += 1
    return result
```
This is then compiled and turned into in invocation script, which I can pass to neon-js as the `script` argument to `query.invokeScript`. When it finishes executing on the RPC node I should have up to 5 values from the enumerator now on the stack.

Live example: https://jsfiddle.net/hal0x2328/3ug45thd

This basic workflow should be implemented in a customizable way in neon-js, available either by providing a `postScript` parameter to be passed to `invokeFunction` and appended to the script before invocation, or as its own function, e.g. `invokeEnumeratorFunction`.

The `postScript` should be flexible and more complex than the example above, allowing for pagination of results but still easy to use in an invocation. For instance: 
```const postScript = buildIteratorScript(startIdx, maxResults)```

**Comment by snowypowers** [comment]
To clarify, is the enumerator interface defined by NEO itself? (is it a built-in function?) 

If it is built-in and works the same for every contract, then yes we should support a way to just simply pull X results onto the stack.

It is impossible to append a post script to `invokefunction` due to how the rpc call is presented. This is not a js implementation issue but a node implementation issue.

`invokescript` is probably where we should target. I agree with you on a helper method that can generate the iterator add on script.

**Comment by snowypowers** [comment]
@hal0x2328 poke for follow up.

**Comment by ediopia** [comment]
I use my own library to fetch paginated data from the chain with order keys.

 static async fetchBlockchainData({
    rpcEndpoint,
    contractScriptHash,
    requestMethod,
    args = [],
    currentPage,
    totalItems,
    pageSize,
    sort = -1,
  }: PaginatedBlockchainProps) {
    try {
      let start;
      let stop;
      const totalPages = Math.ceil(totalItems / pageSize);
      if (sort === 1) {
        start = (currentPage - 1) * pageSize + 1;
        stop = totalPages === currentPage ? totalItems + 1 : start + pageSize;
      } else {
        const skip = (currentPage - 1) * pageSize;
        start = totalPages > 1 ? totalItems - skip : totalItems;
        stop = start - pageSize > 0 ? start - pageSize : 0;
      }

      const items = _.range(start, stop, sort);

      if (items.length > 0) {
        const sb = Neon.create.scriptBuilder();
        items.forEach(i => {
          sb.emitAppCall(contractScriptHash, requestMethod, [
            ...args,
            helpers.convertIntToHexstring(i),
          ]);
        });

        const result = await rpc.Query.invokeScript(sb.str).execute(rpcEndpoint);
        const { stack } = result.result;
        return stack;
      }
      return [];
    } catch (e) {
      throw new Error(e);
    }
  }

**Comment by ediopia** [comment]
I use my own library to fetch paginated data from the chain. 
requestMethod key is a method in the contract that retrieves data by params.
I think this is similar approach that non fungible contracts need.

```
 static async fetchBlockchainData({
    rpcEndpoint,
    contractScriptHash,
    requestMethod,
    args = [],
    currentPage,
    totalItems,
    pageSize,
    sort = -1,
  }: PaginatedBlockchainProps) {
    let start;
    let stop;
    const totalPages = Math.ceil(totalItems / pageSize);
    if (sort === 1) {
      start = (currentPage - 1) * pageSize + 1;
      stop = totalPages === currentPage ? totalItems + 1 : start + pageSize;
    } else {
      const skip = (currentPage - 1) * pageSize;
      start = totalPages > 1 ? totalItems - skip : totalItems;
      stop = start - pageSize > 0 ? start - pageSize : 0;
    }

    const items = _.range(start, stop, sort);

    const sb = Neon.create.scriptBuilder();
    items.forEach(i => {
      sb.emitAppCall(contractScriptHash, requestMethod, [
        ...args,
        helpers.convertIntToHexstring(i),
      ]);
    });
    try {
      const result = await rpc.Query.invokeScript(sb.str).execute(rpcEndpoint);
      const { stack } = result.result;
      return stack;
    } catch (e) {
      throw new Error(e);
    }
  }
```

**Comment by WyattMufson** [comment]
I have a solution to this - just need to test it a bit more.
