### ISSUE TITLE
Calculate the fee according to tx-size

### ISSUE THREAD

**Issue by xulizhe** [CityOfZion/neon-js#453]
In the latest 2.10.2 node, the calculation method has been changed. There is no API or attribute that can obtain tx-byte.

![image](https://user-images.githubusercontent.com/15604297/61789522-7cba3580-ae47-11e9-91c4-a4049b518509.png)

**Comment by snowypowers** [comment]
If you deserialize the transaction into its string representation, every 2 characters represent a byte so just dividing it by 2 will get you your transaction size.

**Comment by MorganDream** [comment]
Could it be better if adding `getSize()` method to transaction type?
Another problem regarding this:
The change of  fee may change the inputs and outputs, thus the size may change again to require more fee. Maybe we could add a method `validateFee()` to return the surplus/lack of fee in a transaction before sending it.

**Comment by xulizhe** [comment]
> If you deserialize the transaction into its string representation, every 2 characters represent a byte so just dividing it by 2 will get you your transaction size.

OK,i will try it

**Comment by xulizhe** [comment]
> Could it be better if adding `getSize()` method to transaction type?
> Another problem regarding this:
> The change of fee may change the inputs and outputs, thus the size may change again to require more fee. Maybe we could add a method `validateFee()` to return the surplus/lack of fee in a transaction before sending it.

that's a good idea!
