### ISSUE TITLE
[feature] add support for neo-local privnet

### ISSUE THREAD

**Issue by dauTT** [CityOfZion/neon-js#455]
For development purposes, it will be nice to connect neon-js to a neo-local privnet. Once done, we can add the same support for neon-wallet: https://github.com/CityOfZion/neon-wallet/issues/871

**Comment by dauTT** [comment]
FYI, I am working on this feature.

**Comment by snowypowers** [comment]
What is currently not supported? Please look at
cityofzion.io/neon-js/docs/en/guides/basic/privnet.html.

**Comment by MorganDream** [comment]
Also this example could help.
http://cityofzion.io/neon-js/docs/en/examples/network.html#initiate-privatenet-instance

**Comment by dauTT** [comment]
Thanks, @snowypowers / @MorganDream, for the advice!!! 

I believe that it should be sufficient for my purpose but if you don't mind I would like to keep this issue open for a few days more before closing it.

**Comment by dauTT** [comment]
@snowypowers / @MorganDream,

neon-wallet is using as a dependency neon-js v3.11.9. With this version, I don't it is possible to connect to a `privnet` as you have explained above. It seems to me that to be able to connect to a `privnet`, I will need to use neon-js verson 4.x.x.  Is my understanding correct or is there a way to connect to a `privnet` with neon-js `v3.11.9` ?
