### ISSUE TITLE
Send transaction with custom attributes

### ISSUE THREAD

**Issue by corollari** [CityOfZion/neon-js#456]
I haven't managed to find in the docs the way to create a contractTransaction (to send some system assets) with custom transaction attributes, such as different values for Hash1, Hash2...

Looking at the source code, it seems that this is somewhat implemented inside the TransactionAttribute class but I haven't managed to find any method inside ContractTransaction that can be used to set these attributes.

How is this done using neon-js?

**Comment by MorganDream** [comment]
Hi Albert. You can add transaction attributes like below:
```js
transaction.addAttribute(tx.TxAttrUsage.Hash1, value);
```

**Comment by corollari** [comment]
Thanks
