### ISSUE TITLE
[Bug] incompatible sync/async encryption interfaces between Wallet and Account class.

### ISSUE THREAD

**Issue by tsmcalister** [CityOfZion/neon-js#460]
It seems like the the `Wallet.encrypt` and therefore `Wallet.encryptAll` functions should return `Promise<boolean>` and `Promise<boolean[]>` respectively.

The `Wallet.encryptAll` function calls the `Wallet.encrypt` function which in turn calls the async `Account.encrypt` function. See https://github.com/CityOfZion/neon-js/blob/master/packages/neon-core/src/wallet/Wallet.ts#L150

otherwise the following code wont work:
```ts
wallet.encryptAll("password")
wallet.export() // fails
```

Workaround is to loop over the `Wallet.accounts` object manually i.e something like this.:

```ts
const waitList = []
for (let acc of wallet.accounts){
    waitList.push(acc.encrypt("password"))
}
Promise.all(waitList).then(() =>
    wallet.export()
)
```

**Comment by MorganDream** [comment]
Yes you are right. We should fix this.

**Comment by MorganDream** [comment]
Shall we close this as PR is merged. @tsmcalister
