### ISSUE TITLE
[Multisig] Inconsistency between neo-cli and neon-js

### ISSUE THREAD

**Issue by MorganDream** [CityOfZion/neon-js#470]
Test Case: 
```ts
const threshold = 3;
const publicKeys = [
      "034fe0ecdb6e24c2281d45333e0dc050ebfa80e974bbe6a687e0048657dd011786",
      "02a4be71f00b63427d70ad80eb11ca888723e10c5e6f3303fe6ba2c843871de6e4",
      "028c7eec6216e19545289c1541304ce7eaa6977eac3608537a688e771860bc723b",
      "0224cd65f8b5a3b393af2df15883d033eabc4ae7f94a923eb1c81831842e1c0ac5"
];
const address = Account.createMultiSig(threshold, publicKeys);
```
The result would be different from neo-cli.

Reason:
neo-cli will sort uncompressed publicKeys - compare x then compare y.
neon-js will not do sorting, and the sorting of just publickey string will not be enough, we need to extract x,y from the publickey string first.

**Comment by Tommo-L** [comment]
neo-cli multisigaddress: AP1tGuChimfUpXaRr7fFfyApFuHSbnuFhD
neon-js multisigaddress: AFtsBJnrD6nGqqUwMY134NgGBQpTU78ypf

C# CreateMultiSigRedeemScript:
```csharp
public static byte[] CreateMultiSigRedeemScript(int m, params ECPoint[] publicKeys)
        {
            if (!(1 <= m && m <= publicKeys.Length && publicKeys.Length <= 1024))
                throw new ArgumentException();
            using (ScriptBuilder sb = new ScriptBuilder())
            {
                sb.EmitPush(m);
                foreach (ECPoint publicKey in publicKeys.OrderBy(p => p))
                {
                    sb.EmitPush(publicKey.EncodePoint(true));
                }
                sb.EmitPush(publicKeys.Length);
                sb.EmitSysCall(InteropService.Neo_Crypto_CheckMultiSig);
                return sb.ToArray();
            }
        }
```

C# ECPoint.CompareTo:
```csharp
public int CompareTo(ECPoint other)
        {
            if (ReferenceEquals(this, other)) return 0;
            int result = X.CompareTo(other.X);
            if (result != 0) return result;
            return Y.CompareTo(other.Y);
        }
```

**Comment by snowypowers** [comment]
The C# implementation meant that for a given set of keys with a given threshold, there is only 1 way to create a multi sig contract. This is not necessarily true and any permutation of public keys are perfectly valid multi sig contracts.

**Comment by Tommo-L** [comment]
Different permutation means different scripthash, address and asset. If a user create a `multisigadress`  in neo-cli, she/he cann't import the address in neon-js, as the sort of addresses.

**Comment by snowypowers** [comment]
You should be importing using a wallet file, not a bunch of public keys. If the wallet file generated by C# is not importable by neon-js then it is a bug. But if it is only a matter of how each implementation creates the address, then its fine. neo-cli just has a more restricted way of creating a multisig address.
