### ISSUE TITLE
getRPCEndpoint() uses servers with expired certificates

### ISSUE THREAD

**Issue by corollari** [CityOfZion/neon-js#471]
## Reproduction steps
Running
```js
import { api, settings } from "@cityofzion/neon-js";
settings.httpsOnly = true;
const provider = new api.neoscan.instance("MainNet");
provider.getRPCEndpoint();
```

leads to the following errors:
![image](https://user-images.githubusercontent.com/32309574/65705649-70f32580-e0bb-11e9-94f6-fc7824b9c493.png)

**Comment by hal0x2328** [comment]
This is a Neoscan issue. A fix was merged in https://github.com/CityOfZion/neo-scan/pull/424 but hasn't yet made its way into production.
