### ISSUE TITLE
[Question] How to add several per-call attributes in a single InvocationTransaction with multiple calls?

### ISSUE THREAD

**Issue by corollari** [CityOfZion/neon-js#472]
Given several smart contract calls that are to be put into a single transaction, it's possible to create a script out of them and create a normal InvocationTransaction with that the following:
```js
let script = Neon.create.script(call1, call2, call3);
```

But how should I go if I want to set a different 0x20 transaction attribute for each one of these calls?

**Comment by snowypowers** [comment]
The script is separate from attributes. You will have to modify the transaction itself calling `addAttribute` to the Transaction object.

**Comment by corollari** [comment]
Thanks, solved.
