### ISSUE TITLE
[Question] How to add a Hash1 boolean attribue?

### ISSUE THREAD

**Issue by corollari** [CityOfZion/neon-js#473]
Looking at <https://github.com/CityOfZion/neon-js/blob/7d28d25ca00bf8f7357d4778f9f2673d6fc44efa/packages/neon-core/src/tx/components/TransactionAttribute.ts> it seems that Hash1-15 attributes must be 16 bytes in size, if I want to store the Boolean value `true` in one of them how should I go about converting that into a 16 byte value?

**Comment by snowypowers** [comment]
I have no idea but usually in computer science you would be thinking about how would you store a value that denotes `True` rather than storing `True` itself. It really depends on how you are using the value. By convention, any non-zero value will evaluate to true when used as a boolean.

**Comment by corollari** [comment]
Yeah well I was trying to find if there was any standardised system that would explain the specific binary encoding used in O3's dAPI, so I was more interested into a specific binary encoding.
Anyway, thanks for the help.
