### ISSUE TITLE
Proper hexstring support

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neon-js#480]
There can be improved support internally for hexstrings to differentiate between endianness, resolve the `0x` sign and support for typing of different hexstrings.

**Comment by snowypowers** [comment]
This issue is primarily for neo3 but it is also a consideration for porting to neo2. However, I would consider it low priority given the potential work and mess.

**Comment by MorganDream** [comment]
I have proposed a PR and want to have discussion with you on below questions:
1. Where should we put these types, and what's the relation between these types and old type-converting apis.
Suggestion: We put these types into module `u`, and stop exporting old type-conversion apis like `str2hextring` and include them into these types, to avoid confusions.

2. `-Like` interfaces
The `-Like` interfaces (e.g. CosignerLike) mostly use string as type, and they will be used to type param for constructors. So shall change the `-Like` interfaces to use new types.
Currently I create a new interface `-Config` to act as the param for constructor.

**Comment by snowypowers** [comment]
1. Yes the `u` module would be the correct place for these. I would bring in the existing methods and unify them under the common namespace.

2. The `-Like` interfaces have been used to represent the json counterpart that we are exporting. It acts as the gateway between the outside world and the neon objects. The constructor must be able to take in a json object and transform it into an neon object. Please continue using the `-Like` interface.

**Comment by MorganDream** [comment]
I think one of the biggest advantages using strong types is that user can use these types when writing codes to avoid confusion. And constructors are used a lot in neon-js. If only `string` is used to initiate some class, the generated instances would probably be invalid or we need to add redundant logic to throw error (e.g. a scripthash param would expect a 30-length string, user may input a "" to be a scripthash, or not even a hex).

Suggestion: 
So I think it's better to type the params for constructors.
Add a static function like `fromJson` to accept the `-Like` param.

**Comment by snowypowers** [comment]
For this to happen, all neon-js classes will have to migrate to the new pattern. Let us see how the Hexstring class works out first before committing.
