### ISSUE TITLE
Update basic tutorials for neo3

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neon-js#498]
Now that most of the basic infrastructure is done, it is time to update tutorials first before proceeding forward. This serves a few purposes:

1. To have a working example of the new flow that was recently implemented in neon-api. Due to major changes, it is currently a big leap from the old style.

2. To have a initial look at the current api to consider future features. I am not clear if the current set of features work well enough. Writing the examples should help clarify this space.

3. Find bugs. There is no full integration tests so there might be bugs or slightly off implementations.

The tutorials can be found in the `examples/basic` folder.

**Comment by Qiao-Jin** [comment]
Hi! When will the [official tutorial](http://cityofzion.io/neon-js/docs/en/installation.html) be updated?

**Comment by snowypowers** [comment]
I dont intend to publish it until we finalise neo3 support and fully update the docs.
