### ISSUE TITLE
Calling emitAppCall without args parameter adds an unnecessary PUSH0 to the script

### ISSUE THREAD

**Issue by djnicholson** [CityOfZion/neon-js#502]
If emitAppCall is called without the args parameter being specified, the script that is generated is prefixed with an unnecessary PUSH0 (0x00) byte. Internally the neon-js code treats the 'undefined' parameter as if it were a boolean false, so pushes a 0 to the stack.  This results in an unexpected 0 being left on the stack after the script is invoked.

Example:

import * as neon from '@cityofzion/neon-js';
// ...
const contractHash = '...'; // replace ... with some valid contract hash
const sb = neon.default.create.scriptBuilder();
const script = sb.emitAppCall(contractHash).str; // script is prefixed with an unexpected 00

**Comment by snowypowers** [comment]
@djnicholson please take a look. Will merge after 24 hours if no comments.

**Comment by djnicholson** [comment]
> @djnicholson please take a look. Will merge after 24 hours if no comments.

PR looks good. Thanks for addressing.
