### ISSUE TITLE
Block or Transaction Validation Failed

### ISSUE THREAD

**Issue by gmaijoe** [CityOfZion/neon-js#504]
I'm getting the following error while sending NEO using NEON-js

{"message":"Error sending NEO","code":500,"details":"Error sending NEO","error":"http://seed1.ngd.network:10332: Block or transaction validation failed.","errorStack":"Error: http://seed1.ngd.network:10332: Block or transaction validation failed.\n    at Query_Query.<anonymous> (/app/node_modules/@cityofzion/neon-js/dist/index.js:7791:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/@cityofzion/neon-js/dist/index.js:7474:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}

```async function sendNEO(res, amount, receiver) {
  let sendNEOPromise = await new Promise(async (resolve, reject) => {
    try {
      const { default: Neon, api, wallet } = require('@cityofzion/neon-js');
      const { rpc } = require('@cityofzion/neon-js');
      const { NEO_PUBLIC } = require('../../../v1/spectrum/util/constants');

      const privateKey = PROD ? process.env.NEO_PRIVATE_KEY : process.env.NEO_PRIVATE_KEY_TEST;
      const myAccount = new wallet.Account(privateKey);

      const Neoscan = new api.neoscan.instance(PROD ? 'MainNet' : 'TestNet');
      let balance = await Neoscan.getBalance(NEO_PUBLIC);

      let tx = Neon.create.contractTx();
      tx.addIntent('NEO', amount, receiver)
        .addRemark('something') // Add an remark
        .calculate(balance) // Now we add in the balance we retrieve from an external API and calculate the required inputs.
        .sign(myAccount.privateKey); // Sign with the private key of the balance

      const hash = tx.hash;
      const serializedTx = tx.serialize();

      await rpc.Query.sendRawTransaction(serializedTx).execute(
        PROD ? 'http://seed8.ngd.network:10332' : 'https://test3.cityofzion.io:443'
      );

      return resolve(['success', hash]);
    } catch (err) {
      console.log(chalk.red('error: ', err));
      postSlackError(`Error sending NEO: ${err}`);
      return reject(errorRespHelper(res, 'Error sending NEO', 500, true, err));
    }
  });
  return sendNEOPromise;
}
```
The code works locally when I call this function but fails when I run it on the server.

We've tried different RPC Clients from http://monitor.cityofzion.io/ but that hasn't worked either.

**Comment by snowypowers** [comment]
One thing i note is the difference in your keys. You are using a static NEO_PUBLIC to retrieve the balance but your private key for signing depends on your env. This wont work for one case unless your private keys are identical.
