### ISSUE TITLE
ClaimGas and SendAsset giving 403 forbidden error

### ISSUE THREAD

**Issue by umanggoyal89** [CityOfZion/neon-js#507]
Hi,

I am trying to use neon-js to send NEO/GAS and claim gas, whenever i try to execute sendAsset function it gives me error 403 forbidded. It used to work correctly but now it is throwing this error. I used the default tutorial for integration in my site.
here is the code i used from the documentation website:

```
const provider = Neon.api.neoscan.instance('TestNet')
const config = {
  provider: 'TestNet'
  address: 'MY_ADDRESS',
  privateKey: 'MY_ADDRESS_PRIVATE_KEY'
}
Neon.api.claimGas(config)
.then((conf) => {
  console.log(conf.response)
})
.catch((error)=>{
console.log(error)
})
```
Does anyone else is having this same problem?
Any help is much appreciated!

**Comment by corollari** [comment]
It maybe a little bit late, but the problem you have encountered is that the code example you are using (the one in `docs/api/plugin/api.md`) is outdated and doesn't work with the current version of neon-js. The correct code is:
```js
const provider = Neon.api.neoscan.instance('TestNet')
const config = {
  api: provider,
  account: new Neon.wallet.Account('MY_ADDRESS_PRIVATE_KEY')
}
Neon.api.claimGas(config)
.then((conf) => {
  console.log(conf.response)
})
.catch((error)=>{
console.log(error)
})
```

#515 fixes this problem by updating the docs with the correct code

**Comment by corollari** [comment]
I had expected this to be closed by 7dde9a0869d43f91520a36329e2496c95e39baaa, well

**Comment by snowypowers** [comment]
[docs](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#closing-an-issue-in-the-same-repository) seem to suggest that it only works if merging into default branch (which is master but we work on dev).

**Comment by corollari** [comment]
I see, makes sense.
