### ISSUE TITLE
Address dose not match with neo3-cli

### ISSUE THREAD

**Issue by Tommo-L** [CityOfZion/neon-js#510]
We have used the latest neo3-cli for generate the address, but the address dose not math with neon-js.

```
privateKey: 
    Hex: bded1d82c369de5e896f5039ade2d8d1942f15449a787d842a742f36c83d83be
    WIF: L3auJnrZymEwaTHokbF2YwB4PKGSZjD49uUMCSMV9cbNZiBH5Lwa

CLI address:  NYXBPFgUM2Wa9wUdtEZV3zk1pLWamNEJB1

/|\
 |
\|/

Neon-js address: AGT6SmEbMsXJJQF5vuVQ7f8diUbj861Tbv
```

neon-js: 5.0.0-next.2
neo-cli:  Combiled from master branch

**Comment by snowypowers** [comment]
yes that is because the latest neo3 cli uses a different address version from neo2. I dont really have the time to keep releasing a new version to keep up with development so I will only consider updating when they release a new preview.

**Comment by Tommo-L** [comment]
Got, thanks
