### ISSUE TITLE
[Cors Error] Timeout request header is not allowed when executing a cross-origin rpc request

### ISSUE THREAD

**Issue by MorganDream** [CityOfZion/neon-js#512]
https://github.com/CityOfZion/neon-js/blob/43b27be1c57c618915ab16bc2e4a3dfd2b20b226/packages/neon-core/src/rpc/RPCClient.ts#L20-L34
And it seems that neo node doesn't add `timeout` in `Access-Control-Allow-Headers`. It will report error in cors preflight request.

**Comment by snowypowers** [comment]
#513 should fix it. timeout was not supposed to be inside the headers but in the config for axios.
