### ISSUE TITLE
GetStorage RPC not hex encoding argument

### ISSUE THREAD

**Issue by revett** [CityOfZion/neon-js#53]
### Problem

As seen [here](https://github.com/neo-project/neo/blob/3846f15ac935515d9ca6e5885bfab52df2b22542/neo/Network/RPC/RpcServer.cs#L181) within the NEO codebase.

The second argument to the `getstorage` RPC endpoint is the storage key, and it should be a hex encoded string.

Currently **neon-js** does not hex encode the string or provide documentation above the function to outline the format of the argument.

Therefore this fails:

```js
api.getStorage(
  'TestNet', 
  '0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9',
  'totalSupply'
).then((response) => {
  console.log(response)
});
```

With the following error:

```
{
  jsonrpc: '2.0',
  id: 1,
  error: {
    code: -2146233033,
    message: 'One of the identified items was in an invalid format.',
    data: 'at Neo.Helper.HexToBytes(String value) in C:\\Users\\me\\NEO\\neo\\neo\\Helper.cs:line 59\n   at Neo.Network.RPC.RpcServer.Process(String method, JArray _params) in C:\\Users\\me\\NEO\\neo\\neo\\Network\\RPC\\RpcServer.cs:line 181\n   at Neo.Network.RPC.RpcServerWithWallet.Process(String method, JArray _params)\n   at Neo.Network.RPC.RpcServer.ProcessRequest(JObject request) in C:\\Users\\me\\NEO\\neo\\neo\\Network\\RPC\\RpcServer.cs:line 371'
  }
}
```

### Solution

Hex encode the argument before calling `queryRPC()`.

**Comment by Ejhfast** [comment]
Thanks for pointing this out! Fixed in dev: https://github.com/CityOfZion/neon-js/commit/9d11ead4107009803c44adae343862e36d36bef1#diff-8e956713da8161c1115505f0422e6812R178
