### ISSUE TITLE
new wallet.Account is taking too long to complete in React Native

### ISSUE THREAD

**Issue by nathanmukena** [CityOfZion/neon-js#538]
I am currently using neon-js on React Native to allow users to create/open their wallets. I typically use the following lines of code:
```
const createWallet = async () => {
    const privateKey = await Neon.decrypt.privateKey(wallet.data.key, wallet.data.hash)
    const newWallet = await new wallet.Account(privateKey)
    return newWallet
}
```
The problem is that these lines can take up to 5 entire minutes in order to execute. Can the Account constructor be optimized?

**Comment by snowypowers** [comment]
I would guess that the decryption is taking up most of the time. I am assuming you are running on a mobile device (since you are using RN) which is underpowered for decrypting keys.
