### ISSUE TITLE
undefined is not an object (evaluating 't.api.getBalance') when executing api.doInvoke

### ISSUE THREAD

**Issue by nathanmukena** [CityOfZion/neon-js#543]
Executing the following code is creating an issue for us when using react-native:
import { api, wallet, u, nep5 } from '@cityofzion/neon-js';
.
.
.
export const submitNeonStory = async (w, promoter_wallet, hex_wallet, hex_challenge) => {
    return api.doInvoke({
        net: env.net,
        url: env.rpcEndpoint,
        account: w,
        script: {
            scriptHash: env.nodis_contract,
            operation: 'submit',
            args: [promoter_wallet, hex_wallet, hex_challenge]
        },
        gas: 0
    })
}

We're getting the following error:
undefined is not an object (evaluating 't.api.getBalance')
- node_modules/@cityofzion/neon-js/dist/browser.js:21:174719 in yt$argument_3
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:274:30 in invoke
* http://packager.q8-kvy.anonymous.nodis.exp.direct/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:176495:43 in <unknown>
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
- node_modules/@cityofzion/neon-js/dist/browser.js:21:174286 in yt
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

**Comment by snowypowers** [comment]
The error is probable [here](https://github.com/CityOfZion/neon-js/blob/f9809848f1383f1f31df72200a67a0f4e0647521/packages/neon-api/src/funcs/fill.ts#L35). What is `w` that you are passing in?

**Comment by nathanmukena** [comment]
This is an open wallet.
`const w = await new wallet.Account(key)`

**Comment by snowypowers** [comment]
are you providing the `api` field of the configuration object? That is the API provider for it to retrieve the balance.

**Comment by nathanmukena** [comment]
I am not providing the api field at the moment. Not sure I ever used this field. Can you provide an example?

**Comment by snowypowers** [comment]
http://cityofzion.io/neon-js/docs/en/examples/smart_contract.html#high-level

**Comment by nathanmukena** [comment]
Thanks. In this example, a variable is assigned to api. Can't seem to find what the value would look like. Is that supposed to be a node URL/
When reverting the neon-js version to 3.9.11, api doesn't seem to be necessary.

**Comment by snowypowers** [comment]
[this](http://cityofzion.io/neon-js/docs/en/guides/basic/doinvoke.html) should give a clearer picture if you are in v4.
