### ISSUE TITLE
extend OpToken for full disassembly support

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neon-js#579]
https://github.com/CityOfZion/neon-js/pull/577 added partial VM script disassembling. I think the functionality could be useful beyond the original reason for creation (multisig parsing). As it stands no translation to the actual syscall names is done, `JMP_x`  and a handful or other instructions will fail to parse. If any of the missing instructions come before the currently supported PUSHINT/PUSHDATA then the remainder of the script will be disassembled incorrectly.

For reference; here is a full NEO3 VM script disassembler https://github.com/CityOfZion/neo3-preview/pull/77

**Comment by snowypowers** [comment]
At the current state, it should be able to breakdown any script. As far as I know, only the PUSH* codes have additional params that require work, the rest are simple opcodes that dont touch the script at all. If there are any, feel free to add the logic. 

Currently:
```
Neon.sc.OpToken.fromScript(Neon.u.HexString.fromBase64("DAUA6HZIFwwUZN9OvpIzTR/H5kvx0eM5QtmQXlEMFM5hb390YX4PxLgFWDryYCojjfY/E8AMCHRyYW5zZmVyDBQwP75r/oFnA5XLgzPAxIoULlM+hkFifVtS").toBigEndian()).map(t => t.toInstruction())
[
  'PUSHDATA1 0500e8764817',
  'PUSHDATA1 1464df4ebe92334d1fc7e64bf1d1e33942d9905e51',
  'PUSHDATA1 14ce616f7f74617e0fc4b805583af2602a238df63f',
  'PUSH3',
  'PACK',
  'PUSHDATA1 087472616e73666572',
  'PUSHDATA1 14303fbe6bfe81670395cb8333c0c48a142e533e86',
  'SYSCALL 627d5b52'
]
```

Notable differences:
- I retained the length byte as part of the params. Probably up for debate whether this is good or bad but it is trivial to change the implementation. A benefit of the current implementation is that reassembling the script is relatively simple.
- I did not translate the syscall to an interop call name.
- No pretty formatting.

One way we can go is to retain how I chose to store the info (`params` field) but for `toInstruction` to remove the length byte and do the interop name translation. AKA change `toInstruction` to produce output similar to your disassembler.

**Comment by ixje** [comment]
* > At the current state, it should be able to breakdown any script.

   For multsig I can believe that, but any contract script will quickly fail. I should have been more explicit in saying `JMP_` and some other instructions will fail to parse *correctly*. Take the `script` from e.g. https://neo3-preview.com/contract/0x59a36cdf1894b373804d9b396b2675df55649b1d 
The reason is simple, it doesn't take into account that instructions like `JMP` also has data

* > I retained the length byte as part of the params. 

   I'd say it's best to remove that, because the length byte is a part of the script encoding and not actual data being pushed onto the stack. 

> One way we can go is to retain how I chose to store the info (params field) but for toInstruction to remove the length byte and do the interop name translation. AKA change toInstruction to produce output similar to your disassembler.

Yes keeping your format but polishing it will full script support is what I was hoping to achieve with the issue report. I'll consider adding it at a later point, because I first have to find my way around and focus on the short term necessary things.

**Comment by snowypowers** [comment]
>The reason is simple, it doesn't take into account that instructions like JMP also have data

Ah I missed that out. I do not have any smart contract experience so my view is limited to the PUSH codes. Those should be a simple add. If you have any more references or examples, feel free to drop them into a new issue. This should be a relatively simple PR with good returns.

> I'd say it's best to remove that, because the length byte is a part of the script encoding and not actual data being pushed onto the stack.

Just to clarify, do you mean to remove it from `params' field or remove it from the `toInstruction` output? I chose to have it remain because `params` currently represents what is being passed into the OpCode. Im all for removing it when outputting `toInstruction` since it deals with encoding.

**Comment by ixje** [comment]
> Ah I missed that out. I do not have any smart contract experience so my view is limited to the PUSH codes. Those should be a simple add. **If you have any more references** or examples, feel free to drop them into a new issue. This should be a relatively simple PR with good returns.

I'd say have a look at the `opcodetable ` in the commit I referenced in the original post. The `size` field there indicates how many `operand` bytes the instruction has. Example
```
  ...
  0x0c: { name: 'PUSHDATA1', size: 1 },
  0x0d: { name: 'PUSHDATA2', size: 2 },
  0x0e: { name: 'PUSHDATA4', size: 4 },
``` 
Just find all of them where size is not 0 :)

> Just to clarify, do you mean to remove it from params field or remove it from the toInstruction output? I chose to have it remain because params currently represents what is being passed into the OpCode. Im all for removing it when outputting toInstruction since it deals with encoding.

So in my understanding `params` equals to what I'd call the instruction `operand`. In this case the length field should not be part of the actual `params` field because it isn't actually data. It's just part of the encoding to indicate the length such that it can be decoded. How else would one know how many bytes are still part of the instruction?

To show this using the C# `neo-vm`
```C#
            byte[] script = new byte[] { 
                (byte)OpCode.PUSHDATA1, 
                0x4, // 1 byte length indicator of the actual data  
                0x11, 0x22, 0x33, 0x44
            };
            Instruction instruction = new Instruction(script, 0); // decode instruction starting from offset 0
            Console.WriteLine(instruction.Operand.ToArray().ToHexString()); // outputs: 11223344
```
we can also look at the actual VM implementation of the `PUSHDATA1` instruction
```C#
                case OpCode.PUSHDATA1:
                case OpCode.PUSHDATA2:
                case OpCode.PUSHDATA4:
                    {
                        AssertMaxItemSize(instruction.Operand.Length); // some overflow check
                        Push(instruction.Operand); // push data onto its internal stack
                        break;
                    }
```

as you can see we only push the `operand` field of an instruction

**Comment by ixje** [comment]
I'll consider this resolved. Printing actual syscall names can be a future improvement.
