### ISSUE TITLE
claim gas

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-js#593]
This feature adds helper functions to handle gas claiming

**Comment by ixje** [comment]
Note: there is an undocumented RPC call `getunclaimedgas` that we can use for querying the unclaimed gas for a single address. It can be called as follows
```
{
  "jsonrpc": "2.0",
  "method": "getunclaimedgas",
  "params": ["PWYLE4NWFUqn7DRK2YhcjsRm3mp5Ts4Eod"],
  "id": 1
}
```
