### ISSUE TITLE
invokeFunction support

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-js#598]
Features to support test invocations(no signature required)

**Comment by ixje** [comment]
We have to consider the naming scheme here
* `doInvoke` (#597) maps to `sendrawtransaction`. Internally it builds a script
* `doTestInvoke` (this PR?) can map to one of 2 RPC calls (both calls do not persist to the chain)
   1. `invokefunction` - requires a contract hash, function name and function arguments
   2. `invokescript` - requires a script builder like `sendrawtransaction`

   So to which of the two do we point it, and what do we call the other one? 

The most straight forward mapping for me would be;
* doTestInvoke -> `invokescript`
* doTestInvokeFunction -> `invokefunction`

Opinions? @lllwvlvwlll @snowypowers

**Comment by snowypowers** [comment]
What is the problem we are trying to solve here first?

Using `invokefunction` has the additional benefit of getting the serialized script back which we can verify if we have all the parameters. I dont think there is a need for 2 methods in this case when they perform the same functionality.

**Comment by ixje** [comment]
`invokefunction` is limited to calling existing smart contract functions
`invokescript` is not limited to existing smart contracts and can execute arbitrary code. Depending on how [this issue](https://github.com/neo-project/neo/issues/1977) is solved, we possible need to be able to invoke a script to get the network fee when using a smart contract as `Signer`.

**Comment by snowypowers** [comment]
Understood. Is there a need to build something on top of the Query and RPCClient objects for these?

**Comment by ixje** [comment]
> Understood. Is there a need to build something on top of the Query and RPCClient objects for these?

Can you elaborate what you have in mind? I currently lack the full understanding of these classes and how `neon-js` for 2.x worked to give an intelligent answer here. My ultimate goal atm is to make sure that by mid november we have a release with which we can;
* transfer NEO
* transfer GAS (requires slightly)
* claim 
Such that `neon-wallet` can become NEO3 ready.

**Comment by snowypowers** [comment]
```
export function doInvoke(config: BigConfigObject) {
getEndpoint();
verifyAccountHasSufficientAssets();
runTestInvokeToGetFeesEstimate();
constructTransaction();
sendTransaction();
}
```
vs
```
export function doTestInvoke(endpoint: string, script:string) {
	const client = new rpc.RPCClient(endpoint);
	return await client.invokeScript(script);
}
```

doInvoke was created in order to reduce the complexity presented. At the moment, this is how `doTestInvoke` looks like in my head. Would need more details to increase the complexity that the method handles.

**Comment by ixje** [comment]
I think `doTestInvoke` for now is indeed what you described. Later on it could be extended to support signers like the [RPC call](https://docs.neo.org/v3/docs/en-us/reference/rpc/latest-version/api/invokescript.html) does 

`doTestInvokeFunction` could probably look something like this
```
function doTestInvokeFunction(contract_hash: HexString | UInt160, methodName: string, methodArguments, signers?: Signers[]) {
1. validate methodName exists in the contract ABI 
2. validate methodArguments against the contract ABI
3. build contract_call script
4. send transaction
} 
```

**Comment by lllwvlvwlll** [comment]
resolved
