### ISSUE TITLE
neon.js v5.0.0

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-js#599]
Initial Production Release of neon.js v5.0.0 for Neo3.  This discussion issue can be used for release and planning.

**Comment by snowypowers** [comment]
From my perspective, the user journeys are:

<details>
<summary> As a wallet developer, I am able to quickly integrate the basic functionality required of a wallet</summary>

The functions are:

- claim GAS
- transfer NEP5 tokens
- Import my NEO2 wallet and upgrade it to NEO3 wallet
- Import my NEO3 wallet
- View my tokens

Currently, the functionality is largely provided by high level methods in `neon-api` and `neon-nep5` that allow wallet developers to focus on creating components to collect the information required to call the facade method.
</details>

<details>
<summary> As a blockchain project dev, I am able to craft a custom workflow to successfully interact with my smart contract</summary>

The dev might be using `neon-js` as an embed (though neoline would be a better solution at the moment for dApi). Else, dev can also be using this as a backend scripting language if the chosen stack is nodejs.

To serve this use case:

- Expose the individual tools used to build the high level methods in `neon-api`.
- Update docstrings within the codebase.
- Export API docs.
- Add examples explaining the workflow in detail.
</details>

<details>
<summary>As a normal developer, I am able to explore the blockchain through neon-js</summary>

This is the normal developer that stumbles upon the blockchain or an onboarding dev trying to get into the scene. We will assume basic blockchain knowledge (of bitcoin and maybe eth) but not the intricate workings of NEO. The core purpose of this use case is to ensure that someone can be quickly setup with something to explore and not stuck in bog.

To serve this use case:

- Provide a self-sufficient privatenet setup
- Provide short runnable examples.
</details>

In order of priority:

code ready
- Update `neon-api` to replace `doInvoke`, `claimGas` and `sendAsset`.
- Refactor `neon-nep5` to a better design.
- Update privatenet to include simple deployed contracts for use.

docs ready
- Update docstrings.
- Improve pipeline for generating docs from runnable examples.
- Add runnable code snippets.

beyond
- Use api-extractor to export API docs
- Add more examples

**Comment by ixje** [comment]
> Import my NEO2 wallet and upgrade it to NEO3 wallet
Import my NEO3 wallet

I didn't want to assume that no mention in the priority list means ready. So to be explicit; Is this fully supported or do any parts for that need work or be validated to work correctly?

 > Refactor neon-nep5 to a better design.

What's wrong with the current design?

> Update privatenet to include simple deployed contracts for use.

Please elaborate what this means

**Comment by snowypowers** [comment]
The support for upgrading a key is complete with `wallet/upgrade.ts`. `nep2.ts` has also been reworked to successfully work with both NEO2&3. Currently, the upgrade works by taking in an Account object with an optional password and returning a new NEO3 Account object. We can consider if we want to work on a method that upgrades the entire JSON wallet file.

The current neon-nep5 design establishes the ABI as a generator. So the code looks like:

```
abi.balanceOf(scriptHash, address)(sb);
```
It is built specifically for ScriptBuilder and is pretty coupled. Changing it to emit a string would be more flexible. I was also thinking of an alternative putting the contract as the core object:
```
const contract: NeonContract = new Nep5Contract(scriptHash);
const tokens: OpToken[] = contract.balanceOf(address);
```

For privatenet, I would like to have a basic NEP5 ICO contract setup so `mintToken` is testable, contracts with methods returning maps and array objects for wider testing.

**Comment by ixje** [comment]
oh what you name "privatenet" is part of your CI setup
