### ISSUE TITLE
Question: RPC multi-request support?

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neon-js#613]
The jsonrpc standard supports sending an array of request objects (and receiving an array of response objects), hence the `id` field to differentiate. Does `neon-js` already support this feature? 

It would be very beneficial for reducing the number of RPC endpoint hits while retrieving balances for multiple tokens for a single address (think neon-wallet as use-case). For NEO2 I believe `neon-js` uses NEOSCAN as API provider for retrieving the balances, for NEO3 (assuming all NEP5 tokens) we would have to send a `rpc.invokeFunction` call for each token.

**Comment by snowypowers** [comment]
Its not currently supported but yes, we should support it.

**Comment by ixje** [comment]
@snowypowers #812 solves this, right?

**Comment by snowypowers** [comment]
Yes it should.
