### ISSUE TITLE
Some possible incorrect value with Neon.sc.ContractParam.byteArray(value, 'fixed8')

### ISSUE THREAD

**Issue by igormcoelho** [CityOfZion/neon-js#615]
Hello guys!
Me and @vncoelho had some issue with method `Neon.sc.ContractParam.byteArray(value, 'fixed8')`, that was being limited by "92233720368.54775807 -> 92233720368.54775808"... on the other hand, method `Neon.default.u.num2fixed8(value))` seemed to return the correct value.
Sorry for not digging deeper now, I'm in a rush, but I just wanted to record that, for some future investigations. If I'm wrong, please just close it. 
Thanks!!

**Comment by igormcoelho** [comment]
Reference: https://github.com/NeoResearch/neocompiler-eco/commit/b05d681df53a1ebad4f748af2c028ae7be2a7c87

**Comment by snowypowers** [comment]
There is an internal check when using the byteArray method for Fixed8 conversion. You seem to be passing a number that is outside the range of Fixed8 so some checks will fail depending on how you pass it in.

**Comment by vncoelho** [comment]
Solved on Neo 3x Next branch. https://github.com/CityOfZion/neon-js/commit/5c45671d116c7bc312429c4f32e3f11561378000
