### ISSUE TITLE
v5.0.0-next.5 Release Banner

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-js#623]
This issue is a stub to create a release announcement banner

Main Bullets for copy:

* Deploy Smart Contracts
* Interact with Smart Contracts( test and published invocations )
* Claim GAS

**Comment by J-G-W** [comment]
![image](https://user-images.githubusercontent.com/36457062/98128247-930aca00-1eaf-11eb-8a67-f4f21c2b49f5.png)

**Comment by J-G-W** [comment]
![image](https://user-images.githubusercontent.com/36457062/98128717-27752c80-1eb0-11eb-984d-6be8506fdb45.png)

**Comment by lllwvlvwlll** [comment]
Thanks!
