### ISSUE TITLE
Enhance NEP5 module to support casting by stack type

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-js#641]
Currently the NEP5 module returns the raw response for balances.  In the field there are non-compliant NEP5 tokens which return integers instead of byte[] causing parse issues.  This enhancement will add support for review the stack response `type` field in order to align the two response types into the expected format.

**Comment by RavenXce** [comment]
Fwiw, I think `BalanceOf` should return `BigInteger` in the latest NEP-5 / NEP-17 spec? 
https://github.com/neo-project/proposals/blob/master/obsolete/nep-5.mediawiki#balanceof

So actually all tokens returning `byte[]` are non-compliant (probably due old compiler?) 🤣
