### ISSUE TITLE
Support for calling custom RPC methods in @cityofzion/neon-core@5.0.0-next.5

### ISSUE THREAD

**Issue by djnicholson** [CityOfZion/neon-js#672]
In `@cityofzion/neon-core@5.0.0-next.4` I could use the RPCClient class to call arbitrary RPC methods. I was using this in places where I need to call a method not yet supported by neon-core (e.g. `getapplicationlog`, `invokefunction`) and for calling neo-express custom methods that will never be supported by neon-core (e.g. `expressgetpopulatedblocks`).

My code would look something like this:

```
          const result = (await this.rpcClient.query({
            method: "expressgetpopulatedblocks",
            params: [count, start],
            id: this.rpcId++,
            jsonrpc: "2.0",
          })) as { blocks: number[]; cacheId: string };
```

As of `@cityofzion/neon-core@5.0.0-next.5` there is no longer a `query` method.  Is there any other way for me to achieve the same result?

**Comment by snowypowers** [comment]
The name is slightly different but the core functionality of arbitrary JSON RPC calls still remains in `execute`. See https://github.com/CityOfZion/neon-js/blob/79c668690d59090f6ae12e6f748b635b1ad1d6fa/packages/neon-core/src/rpc/clients/RpcDispatcher.ts#L63.

RpcDispatcher is the base class so all the inherited classes such as `RPCClient` should have `execute`.

**Comment by djnicholson** [comment]
Thanks @snowypowers. What is the suggested way to construct a `Query` object for an arbitrary RPC method?

**Comment by djnicholson** [comment]
> Thanks @snowypowers. What is the suggested way to construct a Query object for an arbitrary RPC method? 

Disregard. I just realized it has a constructor that takes an object similar to the old `query` method!
