### ISSUE TITLE
Allow supplying a scriptHash instead of a publicKey when building transactions

### ISSUE THREAD

**Issue by RavenXce** [CityOfZion/neon-js#70]
The current params required for building a txn uses an encoded public key instead of a script hash.
(See: https://github.com/CityOfZion/neon-js/blob/master/src/transactions/create.js#L53)

This causes problems when trying to use the library to build dapps where the smart contract to withdraw from / interact with will not have a public key.

Since the only usage of this key seems to be in `calculateInputs` where it is converted back to a scriptHash anyway, it would be nice to just accept a scriptHash from the start instead.

(See: https://github.com/CityOfZion/neon-js/blob/master/src/transactions/create.js#L126)

**Comment by RavenXce** [comment]
I think 
https://github.com/CityOfZion/neon-js/pull/67 solves this, feel free to close!

**Comment by snowypowers** [comment]
The PR will utilise the address field provided by the `balance` object to derive the scriptHash. There shouldn't be any problem as scriptHash and address are reversible.
