### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by bettybao1209** [CityOfZion/neon-js#701]
![image](https://user-images.githubusercontent.com/12050350/115516265-855bcc00-a2b8-11eb-80c6-91441c20cd29.png)

![image](https://user-images.githubusercontent.com/12050350/115516333-99073280-a2b8-11eb-9dde-e916ca3013df.png)

Hi, I used the `createScript` method to create the script, while it throws the exception with the information of `ReferenceError: TextEncoder is not defined`.   
I use the `neon-js-5.0.0-next.7` version which I expect for neo rc1.

**Comment by ixje** [comment]
There was this PR that seemed to fixed it previously https://github.com/CityOfZion/neon-js/pull/659 but I don't see that back in the latest code in the `next` branch. I don't know if it moved and/or why, so I'll leave this for @snowypowers

**Comment by snowypowers** [comment]
What's your nodejs version? Or is this on a browser?

I removed the node10 support since it is out of lts.

**Comment by bettybao1209** [comment]
> What's your nodejs version? Or is this on a browser?
The version is v15.10.0.

**Comment by bettybao1209** [comment]
I add back the code in https://github.com/CityOfZion/neon-js/pull/659/files and it works well.

**Comment by snowypowers** [comment]
```
Welcome to Node.js v15.14.0.
Type ".help" for more information.
> var Neon = require("@cityofzion/neon-js")
undefined
> var sb = new Neon.sc.ScriptBuilder()
undefined
> sb.emitString("test").build()
'0c0474657374'
> new Neon.wallet.Account("L1QqQJnpBwbsPGAuutuzPTac8piqvbR1HRjrY5qHup48TBCBFe4g").address
'NQrEVKgpx2qEg6DpVMT5H8kFa7kc2DFgqS'
```

Tried this on v12, v14 and browser too. I cannot reproduce the issue.

**Comment by bettybao1209** [comment]
I ran the code in typescript and it always throws the same exception. Is it possible to keep the code in the next release?

**Comment by bettybao1209** [comment]
```
import util from 'util';
global.TextEncoder = util.TextEncoder;
```

After I add these two lines, it works with the released next-7 version.

**Comment by snowypowers** [comment]
Yes we are relying on `global.TextEncoder` for the class definition. [v15 docs](https://nodejs.org/docs/latest-v15.x/api/globals.html) indicate that it is available. Please check your node environment. Its either not v15 or its corrupted in some way. The global reference was only added in v12.

**Comment by bokuns** [comment]
> Yes we are relying on `global.TextEncoder` for the class definition. [v15 docs](https://nodejs.org/docs/latest-v15.x/api/globals.html) indicate that it is available. Please check your node environment. Its either not v15 or its corrupted in some way. The global reference was only added in v12.

In this case, I think it's better to declare ```global.TextEncoder``` inside the Neon package since from your previous comment, it was intended to be working on v12 and v14 as well. Besides, v15 is not a LTS anyway so others with current LTS node env could have the same issue.

**Comment by snowypowers** [comment]
The tests in this repository run against v12 and v14 so it works for the current LTS versions. I do not understand your concern here. Please clarify.

**Comment by bokuns** [comment]
It would throw errors in typescript.

**Comment by snowypowers** [comment]
Do you have a setup that can reproduce the error? I did mention above that the main issue is that I cannot reproduce the error. If you can provide that I can dig into it.

> It would throw errors in typescript.

My tests are written in typescript. Anyway, they are ultimately transpiled down to javascript for execution if you are in the node environment.

**Comment by bokuns** [comment]
Here's the [repo](https://github.com/bettybao1209/Neo-ID). After cloning it, go to ```seraph-id-sdk```, and do:
```
yarn
yarn build
yarn test issuer-contract.test.ts
```
If I remove ```global.TextEncoder = util.TextEncoder``` from ```seraph-id-sdk/src/contract-base.ts```, I would get the error in yarn test (Node v14.15.0):
```
sendSignedTransaction error: ReferenceError: TextEncoder is not defined
```
(You can ignore other 127.0.0.1 conn refused errors)

**Comment by snowypowers** [comment]
Hi I root caused the problem to be an issue with jest and the environment. You are using jest with the default testEnvironment which is `jsdom`. There is a [bug](https://github.com/jsdom/jsdom/issues/2524) with `jsdom` where TextEncoder is not available within the global namespace. 

`neon-js` runs tests with the [node](https://github.com/CityOfZion/neon-js/blob/36d7c36324664bb4ee2f69db6ec4cdc9184b8d37/jest.config.js#L2) environment thus we did not encounter such an issue.

To fix this, you either use a node test environment or amend your global environment with the correct globals.

**Comment by bettybao1209** [comment]
> To fix this, you either use a node test environment or amend your global environment with the correct globals.

Yes, by specifying `--env=node` it seems to fix the TextEncoder issue.
