### ISSUE TITLE
Usage guide show `AccessDenied`

### ISSUE THREAD

**Issue by bettybao1209** [CityOfZion/neon-js#702]
The link in the [README](https://cityofzion.io/neon-js/docs/en/guides/basic/sendasset.html) seems inaccessible. So could you tell me where I can get the guide?

**Comment by ixje** [comment]
@lllwvlvwlll I've seen this "access denied" stuff before and not sure what is triggering this. Is this actually a 404 or some AWS rights issue?

**Comment by ixje** [comment]
@bettybao1209 there are 2 interfaces
- NetworkFacade -> [readme](https://github.com/CityOfZion/neon-js/blob/next/docs/guides/basic/facade.md)
- experimental -> [readme](https://github.com/CityOfZion/neon-js/blob/next/packages/neon-js/src/experimental/README.md)

We are aware that the documentation needs work
