### ISSUE TITLE
How to use the ` calculateNetworkFee`, ` getFeeInformation `  in typescript?

### ISSUE THREAD

**Issue by bettybao1209** [CityOfZion/neon-js#703]
```
import neonCore, { rpc, tx, u, sc, wallet } from '@cityofzion/neon-core';
import neonJs from "@cityofzion/neon-js";
const plugin = neonJs(neonCore);
```

In order to calculate the NetworkFee, I import the two functions in this way. While it throws the compile exception saying `neon_js_1.default is not a function`.  I use it in typescript.
I also turn off the `allowSyntheticDefaultImports`.

**Comment by snowypowers** [comment]
`neonJs` is already a preconstructed package. You should be able to access the api package directly:

```
import {api} from "@cityofzion/neon-js";
```

**Comment by bettybao1209** [comment]
So can we import the `api` since it is not exported?

**Comment by snowypowers** [comment]
I realised that the typings exported was wrong due to some configuration issue with webpack. I have tried to fix it and tested that it works with the newest version. Please update to `v5.0.0-next.9` and try it.

**Comment by ixje** [comment]
@bettybao1209 can you let us know if the `next.9` fixed the problem so we can close the issue?

**Comment by bettybao1209** [comment]
> @bettybao1209 can you let us know if the `next.9` fixed the problem so we can close the issue?

yes, I use the latest release and it works. Thanks.
