### ISSUE TITLE
`invokeScript` toBase64 error 

### ISSUE THREAD

**Issue by bettybao1209** [CityOfZion/neon-js#708]
![image](https://user-images.githubusercontent.com/12050350/116047067-45288f00-a6a6-11eb-8cc2-25211da2eba6.png)

For script `0c04746573740c047465737412c01f0c0e7265676973746572536368656d610c145a0fc193a432c668775c7384d47cc0abbd2ba48a41627d5b52`, here I found the u.HexString.fromHex(script) outputs the base64 string `Ult9YkGKpCu9q8B81IRzXHdoxjKkk8EPWhQMYW1laGNTcmV0c2lnZXIODB/AEnRzZXQEDHRzZXQEDA==`, while it is expected to be `DAR0ZXN0DAR0ZXN0EsAfDA5yZWdpc3RlclNjaGVtYQwUWg/Bk6Qyxmh3XHOE1HzAq70rpIpBYn1bUg==`.

**Comment by ixje** [comment]
reverse the script data  `u.HexString.fromHex(script, false)` (note that in your screenshot you specify `true` as second argument)

**Comment by bettybao1209** [comment]
> reverse the script data `u.HexString.fromHex(script, false)` (note that in your screenshot you specify `true` as second argument)

`0c04746573740c047465737412c01f0c0e7265676973746572536368656d610c145a0fc193a432c668775c7384d47cc0abbd2ba48a41627d5b52`  is in LittleEndian, and HexString.fromHex uses big endian by default, isn't?

**Comment by ixje** [comment]
Yes fromHex is big endian by default afaik. All I know is that I can confirm (although using Python) that it is a data order issue.
```python
In [1]: import binascii

In [2]: import base64

In [3]: script = binascii.unhexlify(b'0c04746573740c047465737412c01f0c0e7265676973746572536368656d610c145a0fc193a432c668775c7384d47cc0abbd2ba48a41627d5b52')

In [4]: script_reversed = bytearray(script)

In [5]: script_reversed.reverse()

In [6]: base64.b64encode(script)
Out[6]: b'DAR0ZXN0DAR0ZXN0EsAfDA5yZWdpc3RlclNjaGVtYQwUWg/Bk6Qyxmh3XHOE1HzAq70rpIpBYn1bUg=='

In [7]: base64.b64encode(script_reversed)
Out[7]: b'Ult9YkGKpCu9q8B81IRzXHdoxjKkk8EPWhQMYW1laGNTcmV0c2lnZXIODB/AEnRzZXQEDHRzZXQEDA=='
```

**Comment by ixje** [comment]
@snowypowers pinging you as this seems to be another case of confusion on how to input data properly.

**Comment by bettybao1209** [comment]
It's weird that it works as expected this time when I just use `u.HexString.fromHex(script)` as before.
Not quite sure why this happens, but I will close this issue first.
