### ISSUE TITLE
api.getFeeInformation(client) throws `Invalid Parameter` exception

### ISSUE THREAD

**Issue by bettybao1209** [CityOfZion/neon-js#709]
`const { feePerByte, executionFeeFactor } = await api.getFeeInformation(client);`

![image](https://user-images.githubusercontent.com/12050350/116060147-2df09e00-a6b4-11eb-8be8-0cb2e4ba25c0.png)

![image](https://user-images.githubusercontent.com/12050350/116059991-08639480-a6b4-11eb-86d3-65d80ed4640b.png)

It is confusing that the parameters here are empty?

**Comment by snowypowers** [comment]
Can I get a reproducible setup?

**Comment by bettybao1209** [comment]
> Can I get a reproducible setup?

```
  import {api}  from "@cityofzion/neon-js";
  import { rpc} from '@cityofzion/neon-core';

  const client = new rpc.RPCClient("http://localhost:10332");
  const { feePerByte, executionFeeFactor } = await api.getFeeInformation(client);
```

dependencies set as 
```
"dependencies": {
    "@cityofzion/neon-api": "^5.0.0-next.8",
    "@cityofzion/neon-core": "^5.0.0-next.8",
    "@cityofzion/neon-js": "^5.0.0-next.9"
  },
```

**Comment by snowypowers** [comment]
Please use a single version of `neon-js`. There are javascript intricacies when you mingle 2 versions together. Try depending on all imports purely from `neon-js` instead of importing from `neon-core`.

**Comment by bettybao1209** [comment]
> Please use a single version of `neon-js`. There are javascript intricacies when you mingle 2 versions together. Try depending on all imports purely from `neon-js` instead of importing from `neon-core`.

I change to use `neon-js` only, while it shows the problem as below:
![image](https://user-images.githubusercontent.com/12050350/116202046-bd598800-a76c-11eb-9154-8e16b6e9c411.png)

**Comment by bettybao1209** [comment]
@snowypowers  ping.

**Comment by snowypowers** [comment]
I don't have a good solution at the moment. I do note that you are merely using it as a type check so it should be fine to import it as a type since it doesn't affect the runtime at the end. You will have to rename the import so there is no naming conflict. But for execution code try to stick to using neon-js as much as possible.
