### ISSUE TITLE
It returns Invalid params.

### ISSUE THREAD

**Issue by ediopia** [CityOfZion/neon-js#713]
I am trying to make a custom invoke function. Using NetworkFacade.transferToken, it works fine however my code returns invalid params 

    try {
      const facadePromise = await api.NetworkFacade.fromConfig({
        node: props.nodeUrl,
      });

      const intent = {
        from: new wallet.Account(props.wallet.privateKey),
        to: "NaES6pHFRBibbUkRBm59KNujaxFGaDX69z",
        decimalAmt: 0.00000001,
        contractHash: Neon.CONST.NATIVE_CONTRACT_HASH.GasToken,
      };

      const signingConfig = {
        signingCallback: api.signWithAccount(
          new wallet.Account(props.wallet.privateKey)
        ),
      };

      const sb = new sc.ScriptBuilder();
      sb.emitAppCall(props.script.scriptHash, "symbol", []);
      const txBuilder = new TransactionBuilder();
      txBuilder
        .addScript(sb.build())
        .addSigners({
          account: intent.from.scriptHash,
          scopes: tx.WitnessScope.CalledByEntry,
        })
        .addEmptyWitness(intent.from);

      const txn = txBuilder.build();
      const validateResult = await facadePromise.validate(txn);
      if (!validateResult.valid) {
        throw new Error("Unable to validate transaction");
      }
      const signedTx = await facadePromise.sign(txn, signingConfig);
      const sendResult = await facadePromise
        .getRpcNode()
        .sendRawTransaction(signedTx);
    } catch (e) {
      throw new Error(e);
    }

**Comment by ixje** [comment]
I don't see anything obviously wrong at first sight. Note that you're using the deprecated `emitAppCall` instead of `emitContractCall`. 

Which neon-js version are you using and what version is the RPC node that you're talking to? You can request the node version by RPC using [getversion](https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api/getversion.html)

**Comment by ediopia** [comment]
My RPC version is Neo:3.0.0-rc1 and Neon version neon-js@5.0.0-next.9

**Comment by ixje** [comment]
this worked for me
```javascript
sb.emitContractCall({
      scriptHash: Neon.CONST.NATIVE_CONTRACT_HASH.GasToken,
      operation: "symbol",
    });
```
The  specifying empty `args` or not doesn't matter, so I'm going to guess that the `scriptHash` provided via your props is invalid.


Full script
```javascript
const Neon = require("@cityofzion/neon-js");
const wif = "L1QqQJnpBwbsPGAuutuzPTac8piqvbR1HRjrY5qHup48TBCBFe4g";
const acc = new Neon.wallet.Account(wif);

async function issue713() {
  try {
    const facadePromise = await Neon.api.NetworkFacade.fromConfig({
      node: "http://127.0.0.1:20332",
    });

    const intent = {
      from: acc,
      to: "NaES6pHFRBibbUkRBm59KNujaxFGaDX69z",
      decimalAmt: 0.00000001,
      contractHash: Neon.CONST.NATIVE_CONTRACT_HASH.GasToken,
    };

    const signingConfig = {
      signingCallback: Neon.api.signWithAccount(
        acc
      ),
    };

    const sb = new Neon.sc.ScriptBuilder();
    sb.emitContractCall({
      scriptHash: Neon.CONST.NATIVE_CONTRACT_HASH.GasToken,
      operation: "symbol",
      args: [],
    });
    const txBuilder = new Neon.api.TransactionBuilder();
    txBuilder
      .addScript(sb.build())
      .addSigners({
        account: intent.from.scriptHash,
        scopes: Neon.tx.WitnessScope.CalledByEntry,
      })
      .addEmptyWitness(intent.from);

    const txn = txBuilder.build();
    const validateResult = await facadePromise.validate(txn);
    if (!validateResult.valid) {
      throw new Error("Unable to validate transaction");
    }
    const signedTx = await facadePromise.sign(txn, signingConfig);
    const sendResult = await facadePromise
      .getRpcNode()
      .sendRawTransaction(signedTx);
    console.log(sendResult);
  } catch (e) {
    throw new Error(e);
  }
}

issue713();
```

**Comment by ixje** [comment]
I assume that the `symbol` call was just a minimal example and that you plan to call a function that should be persisted to the chain. If not, note that you can query read only information (like "symbol", "decimals" etc) for free by using the [invokefunction](https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api/invokefunction.html) RPC call. 

If you want to do a single call grabbing multiple method invoke results you can chain the calls using scriptbuilder as done before and call the [invokescript](https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api/invokescript.html) RPC call. Basically all RPC calls except the ones starting with `send` are read-only. Of the `send*` ones `sendrawtransaction` is the only one that does not require an open wallet on the RPC side. Be aware that there is a limit to how many instructions you can execute for free when using `invokescript`, so if it fails with (iirc)  `insufficient gas`, then split the script up in multiple RPC calls.

**Comment by ediopia** [comment]
Weird. This works now. Thanks for trying!
But it has the same issue as https://github.com/CityOfZion/neon-js/issues/714
I am following https://dojo.coz.io/neo3/neon-js/docs/en/guides/basic/transfer.html this instruction to break down to get the right system fee and will compare with NetworkFacade methods.
