### ISSUE TITLE
`NEF deserialization failure - invalid checksum` for NEF files generated by `neon` (RC1) and `ncss` (RC2)

### ISSUE THREAD

**Issue by djnicholson** [CityOfZion/neon-js#725]
I'm using the `@cityofzion/neon-core` npm package, version `5.0.0-next.8`

I cannot deserialize a NEF file generated by the C# compiler.  I get the error `NEF deserialization failure - invalid checksum` when calling `NEF.fromBuffer(...)`. The error originates from [this code](https://github.com/CityOfZion/neon-js/blob/v5.0.0-next.8/packages/neon-core/src/sc/NEF.ts#L115) in neon-core.

I tried with a NEF generated by `neon` and with a NEF generated with the new `ncss` compiler.

I'd like to be able to read a NEF file from disk and deploy it to TestNet using `neon-core`.

**Comment by snowypowers** [comment]
Do you have an example file/hexdump for us to check? We do have a couple of tests checking the NEF code.

@ixje

**Comment by djnicholson** [comment]
Sure! 

This is the one generated using `neon` (version `3.0.0-rc1`): [NeoPetShopContract-RC1.zip](https://github.com/CityOfZion/neon-js/files/6456008/NeoPetShopContract-RC1.zip)

This is the one generated using `nccs` (version `3.0.0-rc2`): [NeoPetShopContract-RC2.zip](https://github.com/CityOfZion/neon-js/files/6456026/NeoPetShopContract-RC2.zip)

**Comment by snowypowers** [comment]
I published `next.10` that includes the fix. Please try it out and close this issue when you verified the functionality.

**Comment by ixje** [comment]
Thanks for the quick fix @snowypowers ❤️

**Comment by ixje** [comment]
@djnicholson note that `next.10` is for `rc2`. The NEF is the same but other areas can differ, so be aware.

**Comment by djnicholson** [comment]
I just tried deploying my contract to RC2 TestNet using `next.10`.  

I get a different error now: `RpcDispatcher.execute` gets the following RPC error:

```
{
  "jsonrpc": "2.0",
  "id": 1234,
  "error": {
    "code": -500,
    "message": "Invalid",
    "data": "   at Neo.Plugins.RpcServer.GetRelayResult(VerifyResult reason, UInt256 hash)\n   at Neo.Plugins.RpcServer.SendRawTransaction(JArray _params)\n   at Neo.Plugins.RpcServer.ProcessRequest(HttpContext context, JObject request)"
  }
}
```

I'm still using the experiemental `deployCOntract` method found here: https://github.com/CityOfZion/neon-js/blob/next/packages/neon-js/src/experimental/helpers.ts (Let me know if I should no longer be using that!)

[This is my contract](https://github.com/CityOfZion/neon-js/files/6504490/sc.zip)

**Comment by ixje** [comment]
Did you also update your wallet to RC2? Addresses have changed so it could very well be that you're trying to deploy from an account without funds.

**Comment by ixje** [comment]
The issue description of https://github.com/CityOfZion/neon-js/issues/741 makes me believe this issue is resolved. If not, please drop a message and we can reopen
