### ISSUE TITLE
NEP-6 wallets created by neon-js have incorrect casing for `isDefault`

### ISSUE THREAD

**Issue by djnicholson** [CityOfZion/neon-js#736]
Neo code expects something like this:
```
{
  "name": "...",
  "version": "1.0",
  "scrypt": { ... },
  "accounts": [
    {
      ...
      "isDefault": true,
      ...
      }
    }
  ]
}

```
but neon-js produces something like this:
```
{
  "name": "...",
  "version": "1.0",
  "scrypt": { ... },
  "accounts": [
    {
      ...
      "isdefault": true,
      ...
      }
    }
  ]
}
```

(Note the casing of `isDefault`)

**Comment by djnicholson** [comment]
Related to: https://github.com/neo-project/neo/issues/2474

**Comment by snowypowers** [comment]
https://github.com/neo-project/proposals/blob/master/nep-6.mediawiki

The standard has always be `isDefault`. If it is amended, we should be appending the details to the proposal.

**Comment by ixje** [comment]
The problem is that `wallet.export()` produces `isdefault` instead of `isDefault`. Unfortunately Erik Zhang thinks updating the NEP is the wrong choice and instead prefers having 1 json property in the whole code base that isn't all lower-case 🤦
