### ISSUE TITLE
Cannot invoke contract on TestNet using `experimental` code

### ISSUE THREAD

**Issue by djnicholson** [CityOfZion/neon-js#741]
I'm trying to invoke a contract I have deployed to RC2 TestNet using the "experimental" code in neon-js.

This is my code:

```
const contract = new neonExperimental.SmartContract(
  neonCore.u.HexString.fromHex("0xbad1cf1f1fb3eb80a8852ce4bd691fb64dfec8ba"),
  {
    networkMagic: 1951352142,
    rpcAddress: "http://seed3t.neo.org:20332",
    account: new neonCore.wallet.Account("88a891f6ff5533a974dc47c129cef005a05e327c3f4500217bed7ee93af4fb3b"),
  }
);

await contract.invoke("adoptPet", [ neonCore.sc.ContractParam.integer(4) ]);
```

The call to `sendRawTransaction` from within the `invoke` code gets an RPC error: 

```
{
  "jsonrpc": "2.0",
  "id": 1234,
  "error": {
    "code": -500,
    "message": "Invalid",
    "data": "   at Neo.Plugins.RpcServer.GetRelayResult(VerifyResult reason, UInt256 hash)\r\n   at Neo.Plugins.RpcServer.SendRawTransaction(JArray _params)\r\n   at Neo.Plugins.RpcServer.ProcessRequest(HttpContext context, JObject request)"
  }
}
```

- `neonCore` is imported from `"@cityofzion/neon-core": "^5.0.0-next.10"`
- `neonExperimental` is the code found at https://github.com/CityOfZion/neon-js/tree/next/packages/neon-js/src/experimental
- `0xbad1cf1f1fb3eb80a8852ce4bd691fb64dfec8ba` is an actual contract deployed to TestNet ([source](https://github.com/ngdenterprise/neo-pet-shop-electron/blob/master/NeoPetShop/NeoPetShopContract.cs))
- `88a891f6ff5533a974dc47c129cef005a05e327c3f4500217bed7ee93af4fb3b` is a private key to a wallet that (at the time of writing) has 500 TestNet GAS
- `1951352142` is the value of `CONST.MAGIC_NUMBER.TestNet` in `"@cityofzion/neon-core": "^5.0.0-next.10"`

**Comment by ixje** [comment]
Your network magic is wrong, which is part of the signed transaction data, therefore your TX will fail to validate.
The correct network magic for RC2 and RC3 is `844378958`

**Comment by ixje** [comment]
We actually had the network magic updated in https://github.com/CityOfZion/neon-js/pull/727 but seems like we never did a release after that. I just attempted to release `next.11`, which has a tag now here on github https://github.com/CityOfZion/neon-js/releases/tag/v5.0.0-next.11 but there seems to be something broken for pushing to NPM. I've asked @snowypowers to look at that. Hopefully by the time you see this it is resolved

**Comment by djnicholson** [comment]
Working as of `next.11` -- thanks!
