### ISSUE TITLE
Is there any way to listen to newly published blocks at neo?

### ISSUE THREAD

**Issue by gitloverr** [CityOfZion/neon-js#746]
hi everyone,

can I subscribe to a channel for listen the newly published block information via websocket or like this from my local node on NEO 2.12.2?

If yes, how can I do that?

Is there any way?

thank you

**Comment by snowypowers** [comment]
Such a channel needs to exist on the node side first. Currently there is quite a lack of support on the node side so we have not put in effort to support it.
