### ISSUE TITLE
Cannot find namespace 'wallet'.ts

### ISSUE THREAD

**Issue by bettybao1209** [CityOfZion/neon-js#747]
![image](https://user-images.githubusercontent.com/12050350/121652378-2a7f6d80-cace-11eb-8b1c-702e1058a8fe.png)

Hello, I use the neonjs in nodejs, while it shows the error above. Could you tell me where I am wrong?

**Comment by snowypowers** [comment]
This is an issue with the type namespaces that I cant figure out how to resolve. My workaround would be to use the neon-core dev dependency and import the types. This should not interfere with bundle size as the typescript types are stripped out after transpliation.

**Comment by bettybao1209** [comment]
> This is an issue with the type namespaces that I cant figure out how to resolve. My workaround would be to use the neon-core dev dependency and import the types. This should not interfere with bundle size as the typescript types are stripped out after transpliation.

Yes, I import from neon-core instead and it works.
