### ISSUE TITLE
Is CONST.ASSETS deprecating?

### ISSUE THREAD

**Issue by rockacola** [CityOfZion/neon-js#75]
I do not see it been used in the codebase and appears that it may have been replaced with `CONST.ASSET_ID`.

I can see `CONST.ASSETS` been refactored and populated by array of objects oppose to key value pairs. Example:

```js
export const ASSETS = [
  { symbol: 'NEO', hash: 'c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b', type: 'GoverningToken' },
  { symbol: 'GAS', hash: '602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7', type: 'UtilityToken' },
]
```

This will allows more advanced query, such as finding symbol by asset hash:

```js
const symbol = CONST.ASSETS.find((a) => (a.hash === 'c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b')).symbol
```

**Comment by snowypowers** [comment]
It is currently used only in `transactions/core` to translate hash to symbol. `ASSET_ID` currently translates symbol to hash.

If we refactor, I guess we can eliminate `ASSET_ID` as `ASSET` will serve both purposes. The downside would be making the code a bit harder to read  when looking up an const but I guess the flexibility improvement is immense.

The other option could be keeping the keys but replacing the values with the Asset Object to allow simple lookup.

Ultimately, do we want to the code to look like

```
ASSETS.find((a) => a.symbol === 'GAS').symbol
```
or 
```
ASSETS.GAS.symbol
```

**Comment by rockacola** [comment]
For now, I see no harm maintaining 2 copies of asset related constants:
* The `ASSET_ID` dictionary covers 99% of current usages, and works as it is.
* And if needed, we then introduce `ASSETS` object array for more advanced reference.
* Have helper class/methods (such as `AssetHelper.getSymbolByHash()`) for easier reference thus reduce potential bugs.

Your proposed nested object will work just as well:
* We reduce duplicates, at cost of ability to query natively
* Helper class/methods will be more important in this scenario, shall there be a need for advanced reference.

**Comment by snowypowers** [comment]
Currently, there isn't a significant reason pushing me to either side... refactoring will not do anything now either. There are only 2 assets available now so its hard to see any future expectations

**Comment by jeroenptrs** [comment]
I don't mind taking a crack at it, including newer mainnet tokens as well if you'd like.
Gives me a small intro to the codebase (been ploughing through it regardless) and that way I can implement it as @rockacola defined in the initial comment.

**Comment by mrkingfoxx** [comment]
> I do not see it been used in the codebase and appears that it may have been replaced with `CONST.ASSET_ID`.
> 
> I can see `CONST.ASSETS` been refactored and populated by array of objects oppose to key value pairs. Example:
> 
> ```js
> export const ASSETS = [
>   { symbol: 'NEO', hash: 'c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b', type: 'GoverningToken' },
>   { symbol: 'GAS', hash: '602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7', type: 'UtilityToken' },
> ]
> ```
> 
> This will allows more advanced query, such as finding symbol by asset hash:
> 
> ```js
> const symbol = CONST.ASSETS.find((a) => (a.hash === 'c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b')).symbol
> ```
