### ISSUE TITLE
Issues with "secure-random" package using electron

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-js#752]
```
"TypeError: r(...).randomBytes is not a function
    at http://localhost:3000/dist/bundle.js:65423:320808
    at Object.s [as default] (http://localhost:3000/dist/bundle.js:65423:321033)
    at Object.e.generateRandomArray (http://localhost:3000/dist/bundle.js:65423:419575)
    at new h (http://localhost:3000/dist/bundle.js:65423:401277)
    at e.GASContract.transfer (http://localhost:3000/dist/bundle.js:65423:9575)"
 ```
 
 The usage of the `secure-random` package is broken in the electron context within neon-js... Not exactly sure what is going on here as I am able to invoke the method it uses if I copy and paste it into my application:
 

```javascript
function nodeRandom(count, options) {
  var crypto = require('crypto')
  var buf = crypto.randomBytes(count)

  switch (options.type) {
    case 'Array':
      return [].slice.call(buf)
    case 'Buffer':
      return buf
    case 'Uint8Array':
      var arr = new Uint8Array(count)
      for (var i = 0; i < count; ++i) {
        arr[i] = buf.readUInt8(i)
      }
      return arr
    default:
      throw new Error(options.type + ' is unsupported.')
  }
}
```
It only appears to break if I use a method within neon-js that relies on it with the stack trace pointing to the `browser.js` produced by neon-js. It appears as though updates to the way that neon-js is bundled/transpiled has caused this issue

**Comment by snowypowers** [comment]
I made a modification to use `crypto-js` for random byte generation. Maybe you can check that out and see if it works. 

If not, it is possible to just rely on your own crypto module for randomness? I do believe its not too much work to just generate the bytes on your side and then pass it as a private key to the Account object. This should be much easier than trying to debug this transpilation issue with Electron.

**Comment by comountainclimber** [comment]
Fixed with https://github.com/CityOfZion/neon-js/pull/753
