### ISSUE TITLE
`Failed to get system fee` when deploying to TestNet using `neon-js/src/experimental`

### ISSUE THREAD

**Issue by djnicholson** [CityOfZion/neon-js#756]
I am using the code at https://github.com/CityOfZion/neon-js/tree/next/packages/neon-js/src/experimental to deploy contracts to TestNet.  At one point this was working, but currently I get the error `Failed to get system fee`

[This is the (trivial) contract that I am trying to deploy](https://github.com/CityOfZion/neon-js/files/6743745/trivial-contract.zip)

**Comment by ixje** [comment]
I’m currently on holiday without laptop so can’t test, but there should be an exception message after “failed to get systeem fee” that should give more insight into what is going on

**Comment by hal0x2328** [comment]
I think I may know the reason for the failure. When I tested a deployment in the Visual DevTracker, I got the extended exception after the `failed to get system fee` error, which was `One of the identified items was in an invalid format`.

By capturing the failed JSON-RPC request content and comparing it to a successful `deploy` test invoke, I found that the only difference was the way that the scripthashes in the permissions section of the manifest are being sent. In neon-js, they are sent in the test invoke without the `0x` prefix, but in the compiled-generated manifest they have the prefix.

You can compare this line from neon-js: https://github.com/CityOfZion/neon-js/blob/92f96b9ffefdd9a5a4de8bd1043dd38c5a37bbec/packages/neon-core/src/sc/manifest/ContractPermission.ts#L43

to this line from the Neo source code:
https://github.com/neo-project/neo/blob/f9b0b3b5dd873b062a04b52cdeea65480956a4e7/src/neo/SmartContract/Manifest/ContractPermissionDescriptor.cs#L116

neon-js is intentionally stripping off the prefix and ending up with a 40-byte hex-encoded scripthash while parsing and reconstructing the manifest JSON, however, the Neo source will only parse the UInt160 if it is 42 bytes long, thus leading to a malformed manifest and the exception.

**Comment by ixje** [comment]
Glad to hear it’s solved. Maybe hard to see on phone, but how come it suddenly broke? The relevant code on both the neon-js side and the c# side didn’t change in respectively 11 months and 2 years, and deploy definitely worked before
