### ISSUE TITLE
Broken link to documentation web site

### ISSUE THREAD

**Issue by roschler** [CityOfZion/neon-js#759]
On this page:

https://github.com/CityOfZion/neon-js

There is a link under the section tilted **Browser** that says:
```
Find more guides on our documentation website
```
Unfortunately the link given results in a _Access Denied_ error:

https://coz.io/neon-js/docs/en/guides/basic/sendasset.html

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>C01PYQJCBMTJAY0C</RequestId>
<HostId>1G8tA8UJOaUIVzs7k7iyIQLmd6ae/IrEgoawqm/aLLeJxFByxnVpZT8SjPdSEGkAyKkeJ5Qiv+c=</HostId>
</Error>
```
Can someone give me the link to the documentation web site?

**Comment by snowypowers** [comment]
Updated the readme link. The correct link should be https://docs.coz.io/neo2/neon-js/docs/en/guides/basic/sendasset.html
