### ISSUE TITLE
Variable length int endianness

### ISSUE THREAD

**Issue by notatestuser** [CityOfZion/neon-js#77]
I thought `num2VarInt` was doing the right thing until my invocations started failing at the [most inconvenient time](https://git.io/vFHEo). After debugging the node I realised that it was trying to read too much of the byte array, failing on GAS cost deserialization because there was no buffer left. Swapping the bytes around fixed it and the txes went through fine.

[This](https://git.io/vFHEX) is where the wrong var int was coming through - `fd00fd` should be 253 but was becoming 64768 in the node.

I've noticed that we aren't using var ints for big values right now (mostly short array lengths) so I wonder if this was the wrong endianness all along and we are just missing a `reverseHex`.

**Comment by snowypowers** [comment]
yes looks like we are missing a reverseHex in write. i reversed in `readVarInt` but somehow did not do that in `num2VarInt`. Would you like to PR?

**Comment by notatestuser** [comment]
Yep, no problem. Just wanted to double check my findings. Will send over the PR asap.

**Comment by snowypowers** [comment]
yes thanks for the discovery! might be the root of many weird invocation failures... time to write more tests for utils...

**Comment by notatestuser** [comment]
Well with that said (I agree with more testing) the invocations do work surprisingly well. especially considering they were only used for RPX mintTokens in neon so far...
