### ISSUE TITLE
Experimental API contract.invoke forces a single witness with CalledByEntry scope

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-js#781]
The experimental API allows a `signers` array to be passed for `contract.testInvoke` but no such argument exists for `contract.invoke` - instead it creates a single signer object using the sender account, and specifies a scope of `CalledByEntry`: https://github.com/CityOfZion/neon-js/blob/2a9ab4197060707af1990237edb94410876702f7/packages/neon-js/src/experimental/contract.ts#L73

This makes it impossible to invoke certain contract methods that require a more explicit scope, such as `CustomContracts`. `contract.invoke` should probably be modified to allow an optional `signers` array to be passed and only fall back to creating one if it is not provided.

**Comment by ixje** [comment]
solved in released version
