### ISSUE TITLE
 rpc method 'CalculateNetworkFee'

### ISSUE THREAD

**Issue by bettybao1209** [CityOfZion/neon-js#789]
Hi, I'd like to know why we do not call `CalculateNetworkFee` directly since I found in neonjs we get the `feePerByte` and `executionFeeFactor` to calculate fee locally instead.

**Comment by bettybao1209** [comment]
@snowypowers ping

**Comment by ixje** [comment]
Probably because we were not aware of the function at the time of writing. If there is no size limitation to tx, then it makes sense to use the RPC method instead.
