### ISSUE TITLE
Magic number incorrect for N3 Mainnet and Testnet

### ISSUE THREAD

**Issue by cloud8little** [CityOfZion/neon-js#791]
```
> CONST.MAGIC_NUMBER.TestNet
844378958
> CONST.MAGIC_NUMBER.MainNet
5195086

```

Testnet magic shoud be 877933390
Mainnet magic should be 860833102

**Comment by ixje** [comment]
I think you might need to update your neon-js version as they've changed a month ago with this PR https://github.com/CityOfZion/neon-js/pull/779

https://github.com/CityOfZion/neon-js/blob/820e20d3160e46d019c3f65e84d3f9270ffa1588/packages/neon-core/src/consts.ts#L9-L10
