### ISSUE TITLE
Export key as NEP-6 compliant

### ISSUE THREAD

**Issue by amlwwalker** [CityOfZion/neon-js#816]
When exporting a N3 wallet from Neon-JS the resulting json is not NEP-6 compliant:

```js
    w.encrypt(USER_PASSWORD).then(() => {
        accountJson = w.export();
        save("download.json", JSON.stringify(accountJson))
    });
```

The tools all developed by the Neo team expect keys to be imported in [NEP-6 compliant ](https://docs.neo.org/docs/en-us/basic/concept/wallets.html#nep6-files) format such as [this one ](https://github.com/nspcc-dev/neofs-dev-env/blob/master/wallets/wallet.json).

I think it is a reasonably straight forward addition/change to get the current JSON to fit the format of a NEP-6 compliant wallet.

**Comment by snowypowers** [comment]
Can I get more information on the specific portions that are non-compliant? The spec is [here](https://github.com/neo-project/proposals/blob/master/nep-6.mediawiki). The main difference I can tell is the handling of `isDefault` vs `isdefault`.

**Comment by amlwwalker** [comment]
Hey @snowypowers 

The key that is exported from Neon-JS has the format:

```json
{
  "address": "abc123",
  "label": "abc123",
  "isDefault": false,
  "lock": false,
  "key": "abc123",
  "contract": {
    "script": "abc123==",
    "parameters": [
      {
        "name": "signature",
        "type": "Signature"
      }
    ],
    "deployed": false
  }
}
```

the Nep-6 wallet format is

```
{
  "version": "3.0",
  "accounts": [
    {
      "address": "abc123",
      "key": "abc123",
      "label": "",
      "contract": {
        "script": "abc123==",
        "parameters": [
          {
            "name": "parameter0",
            "type": "Signature"
          }
        ],
        "deployed": false
      },
      "lock": false,
      "isdefault": false
    }
  ],
  "scrypt": {
    "n": 16384,
    "r": 8,
    "p": 8
  },
  "extra": {
    "Tokens": null
  }
}
```

I should apologise for the us of the word "compliant" because infact Neon-JS outputs an account, not a wallet, so other apps are expecting the format to be a wallet - can Neon-JS output a wallet with accounts inside?

**Comment by snowypowers** [comment]
https://github.com/CityOfZion/neon-js/blob/master/packages/neon-core/src/wallet/Wallet.ts this should be the NEP6 wallet you are looking for. The `Account` is merely a single account entry within the NEP6 wallet.
