### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neon-js#825]
Check the readme of the `next` branch for for outdated content. 
* Is that Node v8 mentioned in the Setup section still the latest?
* I'd like to suggest to remove Ethan as author for v5 and make that @snowypowers . I feel like the N3 version is a pretty big revamp and I'm a fan of giving credit where credit due. Any opinions on that @lllwvlvwlll ?

**Comment by lllwvlvwlll** [comment]
I agree with your proposal.
