### ISSUE TITLE
v5.0.0 formal release checklist

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neon-js#826]
Today we had a user on Discord wondering if it was safe to use `neon-js` as it looked unmaintained. After a short discussion with the user I understand where that point of view comes from. 
1. **Documentation**; The current documentation is outdated and is still talking about neo3 preview 2, NEP5 and one guide even uses Fixed8 and other outdated code. 
2. **Repo first look**; The last commit on the `master` branch is from July 2021, the `dev` and `neo3` branches are even further back and the `Releases` side bar shows the latest release being May 2020. Without knowing that `next` is the NEO3 branch I would also think the project is abandoned. 

Neo 3 has been live for some months now, and I think that the `next` branch has N3 covered pretty good that I believe it is time to see if we can make a formal release of v5.0.0, no?

Todo
- [x] #820
- [x] #822
- [x] #823
- [x] #824
- [x] #825
- [x] #827
- [x] #831
- [ ] #832

**Comment by snowypowers** [comment]
I have commented or fixed all relevant issues. I don't think cleanup should be a blocker for the release. Is there anything else? I know docs are lacking but we can release the code first.

**Comment by ixje** [comment]
I need to stop reading github by mail as I loose notifications on the web when I can actually do something with it. 

All good enough for me. Let's release it!
