### ISSUE TITLE
Update wiki for N3

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neon-js#831]
1. The wiki has has a release schedule that doesn't seem to have been uphold for a while now. Should we drop mentioning any time schedule to avoid failing to meet readers expectations? 
2. The releasing page(s) now still have a special `Releasing next`. After releasing v5.0.0 this page should be obsolete and can be dropped. I assume the `Releasing latest` information becomes accurate again once the `next` branch is renamed to `dev`?

**Comment by snowypowers** [comment]
Updated wiki, removing release schedule. The release instructions are valid for  `latest` and should not block v5 release. We can do the clean up after the release.
