### ISSUE TITLE
Update package.json for N3

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neon-js#832]
This is the part I'm least familiar with but I think we should be able clean up the file a bit and drop the following scripts?
* release:next
* version:next

**Comment by snowypowers** [comment]
this shouldnt be a blocker we can always clean this up later after the release.

**Comment by ixje** [comment]
fine by me

**Comment by ixje** [comment]
The file looks pretty up to date to me now (at least after #888 and #889)
