### ISSUE TITLE
length of hex string for curve.sign

### ISSUE THREAD

**Issue by bettybao1209** [CityOfZion/neon-js#844]
https://github.com/CityOfZion/neon-js/blob/804b20a34872be3d6ae70bc036bdf367fc50b280/packages/neon-core/src/u/basic/curve.ts#L32
Hi, I'd like to know the length of parameter `message` should be even number, right?

**Comment by ixje** [comment]
it should be even yes

**Comment by bettybao1209** [comment]
> it should be even yes

https://github.com/NeoNEXT/neoline/blob/08f0d7f3d4df0bd30e3e75be61c193ad5d628e37/src/app/popup/notification/signature/signature.component.ts#L49

so I tried to sign the message, of which the length of `serializedTransaction` is odd while it can still output the result. Do you know why?

**Comment by ixje** [comment]
because it is your responsibility that message is a valid hex string and `Buffer.from` (used [here](https://github.com/CityOfZion/neon-js/blob/804b20a34872be3d6ae70bc036bdf367fc50b280/packages/neon-core/src/u/basic/curve.ts#L48)) oddly enough doesn't care if the input is odd or even and just drops 1 character to make it even

**Comment by bettybao1209** [comment]
![image](https://user-images.githubusercontent.com/12050350/164211733-56a326d7-8da5-49e9-8e2e-227bcc2a38a0.png)

![image](https://user-images.githubusercontent.com/12050350/164211991-35f89782-0ea6-4f31-9ad9-5b9286084d7e.png)
![image](https://user-images.githubusercontent.com/12050350/164211989-bb49ec40-962f-4684-bbe7-623d055fea12.png)

Here we invoke the `sign` method, it will call `sha256` which use `hexEncoding.parse(hex)` first the get the` wordArray`, can the `hexEncoding.parse` method take the odd length of the hex string?

**Comment by snowypowers** [comment]
It is possible to introduce an odd-length string [ if `parameterHexString.length` is larger than `0xff`](https://github.com/NeoNEXT/neoline/blob/08f0d7f3d4df0bd30e3e75be61c193ad5d628e37/src/app/popup/notification/signature/signature.component.ts#L64) since the code only pads up to length of 2.
