### ISSUE TITLE
Shouldn't default AddressVersion be 53 not 23?

### ISSUE THREAD

**Issue by devhawk** [CityOfZion/neon-js#858]
`ProtocolSettings` in Neo C# project [sets the default address version](https://github.com/neo-project/neo/blob/17c7358f282434003fd5a12d9885a26e5563377a/src/Neo/ProtocolSettings.cs#L111) to hex value `0x35` which is 53 in decimal

```cs
public static ProtocolSettings Default { get; } = new ProtocolSettings
{
    Network = 0x334F454Eu,
    AddressVersion = 0x35,
    // remaining initialization code omitted
```

Neon.JS appears to be using 23 as the default instead of 53: 

https://github.com/CityOfZion/neon-js/blob/0ee44d4b33a8ce5ae7b46d78c58c8a62c7e96900/packages/neon-core/src/rpc/Protocol.ts#L43

**Comment by ixje** [comment]
that's definitely a NEO2 leftover 
https://github.com/neo-project/neo/blob/0b6526e8df49004fc7c069982084b7f0bcb44f6f/neo/ProtocolSettings.cs#L53
