### ISSUE TITLE
CommonConfig's prioritisationFee is not used and might lead to confusion

### ISSUE THREAD

**Issue by melanke** [CityOfZion/neon-js#864]
https://github.com/CityOfZion/neon-js/blob/804b20a34872be3d6ae70bc036bdf367fc50b280/packages/neon-js/src/experimental/types.ts#L5

**Comment by ixje** [comment]
Yeah that's odd. I swear that it was used in the past as I don't recall `CommonConfig` being a NEO2 thing, but there seems to be some history missing on where it came from. 

Anyway; here are the rules for transaction prioritisation ([ref](https://github.com/neo-project/neo/blob/8e68c3fabf8b7cad3bd27e0c556cbeda17c2b123/src/Neo/Ledger/PoolItem.cs#L46-L57))
```C#
public int CompareTo(Transaction otherTx)
        {
            if (otherTx == null) return 1;
            int ret = (Tx.GetAttribute<HighPriorityAttribute>() != null).CompareTo(otherTx.GetAttribute<HighPriorityAttribute>() != null);
            if (ret != 0) return ret;
            // Fees sorted ascending
            ret = Tx.FeePerByte.CompareTo(otherTx.FeePerByte);
            if (ret != 0) return ret;
            ret = Tx.NetworkFee.CompareTo(otherTx.NetworkFee);
            if (ret != 0) return ret;
            // Transaction hash sorted descending
            return otherTx.Hash.CompareTo(Tx.Hash);
        }
```
So for implementing the feature; when `prioritisationFee` is used we should at least also set the `HighPriority` attribute. It has no cost but is the first thing checked. Then secondly we must increase `networkFee` with the value of `prioritisationFee`.

**Comment by ixje** [comment]
completed in v5.2.0 release
