### ISSUE TITLE
WitnessRule deserialize failed

### ISSUE THREAD

**Issue by xie-yue** [CityOfZion/neon-js#872]
v5.2.0 neo3
neon-core/lib/tx/components/WitnessRule

`serialize() {
        return (this.action.toString(16).padStart(2, "0") + this.condition.serialize());
    }`

`    static deserialize(ss) {
        const action = parseEnum(ss.read(1), WitnessRuleAction);
        ...
    }`

in deserialize, the first param `ss.read(1)` will be 01 (Allow) witch was not defined in `WitnessRuleAction`.
throw an error `01 not found in enum!`

**Comment by xie-yue** [comment]
seems like missed `parseInt`, result of `ss.read(1)` is a string

**Comment by ixje** [comment]
I'll have a look a.s.a.p

**Comment by ixje** [comment]
Expect a PR later in the day (European timezone) fixing this and some other issue I encountered

**Comment by ixje** [comment]
@xie-yue see the PR :point_up: 
Note: a new release might not happen until after the weekend. Waiting for the maintainer approval on the PR

**Comment by EdgeDLT** [comment]
I think I may be having some related errors when it comes to tx serialization. I did a little bit of light testing. With `tx.serialize()` and only the `validUntilBlock` property set, I get the expected hexstring. A few others serialize fine too, like fees.

Trying with only `signers` added gave:
```js
prop.map((p) => (typeof p === "string" ? p : p.serialize())).join(""));
                                                       ^      
TypeError: p.serialize is not a function
```

Trying with only `script` added gave:
```js
throw new Error(`num2hexstring expected a number but got ${typeof num} instead.`);
              ^

Error: num2hexstring expected a number but got undefined instead.
```

**Comment by ixje** [comment]
@xie-yue fyi; https://www.npmjs.com/package/@cityofzion/neon-js/v/5.2.1

**Comment by xie-yue** [comment]
worked perfectly! thx!
