### ISSUE TITLE
BooleanWitnessCondition has no serialize method override

### ISSUE THREAD

**Issue by xie-yue** [CityOfZion/neon-js#876]
in [BooleanWitnessCondition](https://github.com/CityOfZion/neon-js/blob/dev/packages/neon-core/src/tx/components/WitnessCondition.ts#L132)

there is no serialize method override, so `expression` didn't work.
for deserialize read byte for `expression`, next step `deserializeAttributes` throws en error `11 not found in TxAttrUsage!`

related
https://github.com/CityOfZion/neon-js/issues/872
@ixje

**Comment by ixje** [comment]
Sorry to see that. Hopefully the above PR fixes all remaining issues with WitnessConditions. 

As for `deserializeAttributes`. That's a separate issue. Transaction attributes are something only committee members can set and as a result hardly ever seen. The current implementation is actually still based on NEO2

**Comment by ixje** [comment]
@xie-yue fyi; https://www.npmjs.com/package/@cityofzion/neon-js/v/5.2.2

**Comment by xie-yue** [comment]
works great! thx! @ixje
