### ISSUE TITLE
[Feature] Account + Balance integration

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neon-js#88]
# Feature

Account class should be the central object that interactions revolve around. Thus, I would like to have Transaction construction accept an Account class instead of a Balance object. This allows us to reduce the number of arguments as well as make it easy on the mind by centralising the data store (no more maintaining reference to balance, publickey, etc)

## Specifics

- Balance to be under `Account.balance`
- Transaction.createTx to use Account or balance for creation

**Comment by csggene3** [comment]
I'd like to take a crack at it if that's agreeable. There's definite intelligence behind presenting an account with those other parameters passed along. Would there be a larger class though to incorporate the identity verification features and create a person class, or something like an individual person as a corporation, to allow for non-account related data as well as hypothetical multiple accounts to be correlated and passed along?

**Comment by snowypowers** [comment]
yes you can pick it up. There isnt a larger class involved now but there is the Wallet class which holds multiple accounts.

**Comment by snowypowers** [comment]
After consideration, this will be put on hold. There might be better options in having a larger class above to hold this information instead of having the Account class hold all the responsibility.
