### ISSUE TITLE
5.3.0 is much slower on key encryption/decryption than 4.8.0

### ISSUE THREAD

**Issue by roman-khimov** [CityOfZion/neon-js#891]
Simple code like
```
			const acc = new wallet.Account();
			const wall = Neon.create.wallet({ name: 'some' });
			wall.addAccount(acc);
			wall.encrypt(0, password)
```
or
```
			const account = new wallet.Account(parsedWallet.accounts[0].key);
			account.decrypt(password)
```
is 100% portable between 4.8.0 (Legacy) and 5.3.0 (N3). And it effectively does the same NEP-2 crypto behind the scenes. But we've noticed that using 4.8.0 it takes ~2-3 seconds per operation, while using 5.3.0 it takes ~15s. And we're not sure why it happens this way. Scrypt parameters (that can influence) are the same in both versions.

CC @mike-petrov.

**Comment by ixje** [comment]
For completeness sake (as speed can be machine dependent), this is using v4.8.0. Pretty much identical results
![Screenshot 2023-04-12 at 09 20 39](https://user-images.githubusercontent.com/6625537/231382174-ce784123-d3fc-4cd5-b5aa-ed096b2277c5.png)

**Comment by ixje** [comment]
I still can't seem to reproduce
https://codesandbox.io/s/determined-sammet-9y3510?file=/src/App.js
![Screenshot 2023-04-12 at 11 38 08](https://user-images.githubusercontent.com/6625537/231418886-1e276396-1a7d-47a0-9a51-5bab7f7c849d.png)

**Comment by ixje** [comment]
With the `open in new window` "trick" I also get a high delta. 

The `scrypt-js` package version used in `4.8.0` is `3.0.0` vs `3.0.1` for `5.3.0`. The only difference there is `3.0.1` [adds type declarations](https://github.com/ricmoo/scrypt-js/commit/9fe2241cc3aa79e391753f5f0b23bf8511988b5b).

I was about to go to bed so I'm not going to investigate further tonight, but it is an interesting case

**Comment by ixje** [comment]
I'm not sure what todo with this. This seems like an issue with `scrypt-js` + `react` that is exposed through `neon-js`. However, our desktop wallet is also `react` based, uses this part of `neon-js` and doesn't seem to suffer from this issue. 

Note that I get the same slow results using `scrypt-js 3.0.0` (that `neon-js` `4.8.0` uses as with `3.0.1`) using the code below.

```js
import logo from './logo.svg';
import './App.css';
import {Buffer} from 'buffer';
import { scrypt } from "scrypt-js";
function App() {
    const password = Buffer.from("AABB", "hex")
    const salt = Buffer.from("1122", "hex")
    const start = Date.now();
    scrypt(password, salt, 16384, 8, 8, 64).then(() => {
      const end = Date.now();
      console.log("delta: %dms", end - start);
    })


  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```

Maybe @snowypowers has an idea what could be up. Perhaps we can find a native implementation like this emscripten compiled [one](https://github.com/tonyg/js-scrypt) to mask the issue. I know too little about JS/TS or this library to know what requirements a native/compiled library must have to provide a compatible replacement. I consider myself just around 1st line support level on this project.

**Comment by roman-khimov** [comment]
At least we have this issue confirmed now, that's already something, we know it exists. And yeah, it's a strange one.

**Comment by ixje** [comment]
@roman-khimov -> https://www.npmjs.com/package/@cityofzion/neon-js/v/5.4.0
