### ISSUE TITLE
No SSL protection on MainNet API node

### ISSUE THREAD

**Issue by nisargap** [CityOfZion/neon-js#9]
```
http://api.wallet.cityofzion.io
```
Wouldn't all API calls be unencrypted to this link? Couldn't that introduce a possibility for a man-in-the-middle attack?

**Comment by Ejhfast** [comment]
this is not a problem, (1) nothing sensitive is going to the light wallet API, only public information (2) the nature of the Neo network is such that even a man-in-the-middle could not do anything interesting with information going into the RPC

**Comment by Ejhfast** [comment]
also, thanks for suggestion, it never hurts to have https and we will think about for future, but there is no security issue with public APIs

**Comment by mastashake08** [comment]
You can't make a progressive web app calling using the http api this is a problem I am having. Sure I can write my own back end implementation that calls the HTTP api but I am trying to make client side only. Please fix and address.
