### ISSUE TITLE
Crash React Native Builded App using Neonjs 5.4.0

### ISSUE THREAD

**Issue by raulduartep** [CityOfZion/neon-js#901]
Hi, I am getting the error `ReferenceError: Can't find variable: u` when I try to open a builded React Native app using the Neonjs 5.4.0, but it's normal when I run the app with Expo. 

I downgraded to the 5.3.0 version and the builded app works fine, so probably it's a issue that came up with the new version.

I have cloned neonjs and did some tests installing the lib as a local dependency in the app, with that, I came to the conclusion that what is causing this crash is the minimize of neon-core. I also have notice this commit https://github.com/CityOfZion/neon-js/commit/d675a05a2a337999070c855334043fa6e84d9e3e#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519 upgraded the version of some dependencies(Webpack and TenserPlugin) that may be causing the problem.

Can you help me ? :)

**Comment by ixje** [comment]
@snowypowers :point_up:

**Comment by snowypowers** [comment]
Im not too clear on what is happening here. Since you have a local test setup, have you tried reverting the updates to webpack and see if it works? The change also introduced a tsconfig update that changed the emitted js version, that might be another possible culprit.

Sorry but I dont have a RN setup so I cant exactly reproduce and debug it.

**Comment by raulduartep** [comment]
Yes, I have tried to do it, but I couldn't because this commit https://github.com/CityOfZion/neon-js/commit/a96afef14dc03ea526539ffad5021a891db25dde switches from yarn to npm, so how a new package-lock was created, the webpack updated with a slightly more updated version than the old one that was being used in yarn. A commit before it, everything works normally.

**Comment by snowypowers** [comment]
Can you  try #904 and see if it fixes it in RN? Found a possible error to do with ascii vs utf8 chars.

**Comment by raulduartep** [comment]
It worked perfectly, thanks a lot. I only made one change which was to put your solution in the neon-core package, because that's where the error was. Maybe it's interesting to put it in all packages.

Again thank you very much.

**Comment by raulduartep** [comment]
@snowypowers Do you have any estimates of when a new version will be released?

**Comment by snowypowers** [comment]
I will let @ixje handle the releasing.
