### ISSUE TITLE
Add Map into ScriptBuilder

### ISSUE THREAD

**Issue by melanke** [CityOfZion/neon-js#909]
When using the [buildScriptBuilder](https://github.com/CityOfZion/neon-dappkit/blob/9ca024998b0a0060887740a7fffb8be60e570e7d/packages/neon-dappkit/src/NeonInvoker.ts#L171) on NeonInvoker, you will get an error if you use a Map as parameter of an invoke.
This is because when running `emitContractCall`, you'll eventually trigger this error [Unaccounted ContractParamType! : 34](https://github.com/CityOfZion/neon-js/blob/e62d1f2673c38ad956c75cbbf4d4fe74ec60c58a/packages/neon-core/src/sc/ScriptBuilder.ts#L294C1-L294C1)

**Comment by melanke** [comment]
This is a bug introduced on https://github.com/CityOfZion/neon-js/pull/898

**Comment by ixje** [comment]
I assume you will PR to fix?

**Comment by melanke** [comment]
@ixje We have an issue on Clickup to fix this. Probably Raul or Lucas are going to work on it. But on the next Sprint, because they are fully allocated on this one.
