### ISSUE TITLE
Invalid checksum error when deploy contract(version3.6.2)

### ISSUE THREAD

**Issue by Tobeyw** [CityOfZion/neon-js#928]
When we deployed the 3.6.2 version contract with`neonjs`, an` invalid checksum` error occurred. 
I found that the latest version of `n3 compiler 3.6.2` deleted the `MaxScriptLength` field of the `nefFile file`, which changed the calculation method of `chenkSum`. I guess it may be related to this.
https://github.com/neo-project/neo/commit/efa86592d080ebfde685bc87a26177c5bed5431f#diff-e5a9d7d849aceff46a01663d9e6246d09c4c82e49af60f21dc879d05c40481ee

![image](https://github.com/CityOfZion/neon-js/assets/38420178/08d211af-b6d9-4457-9788-b78138011813)

**Comment by ixje** [comment]
The format of the NEF hasn't changed with that commit. It seems to only change the allowed size of the `script` field from `512*1024` (as defined by `MaxScriptLength`) to `ushort.max * 2` (as defined by `ExecutionEngineLimits.Default.MaxItemSize`).

I'll try out the new 3.6.2. compiler and see if I can reproduce

**Comment by luc10921** [comment]
I tried running the `fromBuffer` method using my NEF file generated with the 3.6.2 compiler and it worked.
```ts
    const myNef = sc.NEF.fromBuffer(
      readFileSync(
        "path\\to\\nef\\file"
      )
    )
```

Do you know which neon-js version you are using?

**Comment by Tobeyw** [comment]
`@cityofzion/neon-js": "^5.5.1",`

**Comment by ixje** [comment]
Can you please share the code snippet used that caused the error and also what you now use that works? The checksum in the file seems correct, so this is a strange case and we need a bit more information to investigate.

**Comment by Tobeyw** [comment]
This is the code I deploy the contract with neon-js. [neonjs](https://github.com/Tobeyw/TestN3-neon/blob/1d13f9fe02fc2a58770d78ff69a6947aec318a2f/deployContract.js#L21)

This is the code I deploy the contract with [C#](https://github.com/Tobeyw/TestN3/blob/b0ce2e9d23194e953143f128349fa48321e0bc99/main.cs#L114) and it worked.

**Comment by ixje** [comment]
The `neonjs` code is loading a different file (`\Neo3ContractTest.nef`) than what the C# code is loading (`SampleHelloWorld`, [link](https://github.com/Tobeyw/TestN3/blob/b0ce2e9d23194e953143f128349fa48321e0bc99/main.cs#L115C32-L115C48)). You previously shared `SampleHelloWorld` and that file is correct. I can't say anything about `Neo3ContractTest.nef`

**Comment by Tobeyw** [comment]
This is what I tested with other versions of the contract. It has not been updated. The code is the same, but the files are different. Please ignore it.

**Comment by luc10921** [comment]
The problem was occurring because neon-js had a problem when deserializing a compiler that uses all 64 available characters

And since the compiler you are using is probably some version from the master branch instead of the one at NuGet, the compiler name occupies all 64 chars (`Neo.Compiler.CSharp 3.6.2+c9ccbb646657240053065ec7c7ff02f106d...`).

I created a PR to fix this problem.
