### ISSUE TITLE
Unminified browser.js?

### ISSUE THREAD

**Issue by woodser** [CityOfZion/neon-js#95]
Hi, is an unminified version of lib/browser.js available or can it be created?

Thanks!

**Comment by snowypowers** [comment]
fork and run `npm install && npm build:dev`

Do let me know the use case im interested

**Comment by woodser** [comment]
I'm interested in adding public/private key generation for NEO to http://cryptostorage.com (the site is still pre-launch).

It would be ideal to have a standalone javascript file capable of generating public/private key pairs in the browser.  The source code needs to be unminified so users can audit it.  Do you have any suggestions?  Perhaps your ansy wallet generator is better to use?

**Comment by snowypowers** [comment]
Hmm even when unminified it is quite a chore to assess if the code is truly safe. The easy way out is providing a standalone release that can be downloaded and used with an offline computer. This way only the hash needs to be checked before reading the unpacked source code to ensure it is safe.

If you are merely generating private /public key pairs I suggest just understanding ansy code and implementing it yourself.

**Comment by woodser** [comment]
Do you have any recommendations for how I can get a standalone release that can be used with an offline computer to generate key pairs?  It's fine if the code includes more than key pair generation - it simply won't be used.

Thanks!

**Comment by snowypowers** [comment]
When I meant standalone release, I meant releasing your website on github as a standalone release. Do check out how other offline wallet generators work and how they do stuff.

Like I mentioned, you can either use this or ansy code.

**Comment by woodser** [comment]
Ah, yes.  It will be provided as a standalone application to download and run on an offline computer.  Thanks for your help!
